In [18]:
from sys import path

path.append("../")

from src.utils.result_presentation import get_results_path, present_results

In [27]:
# TODO: `only_last` does not work as intended. It should consider only the last multirun for each
# dataset, regardless of the others.
all_results = get_results_path(only_last=True, specific_path="multirun_2025-10-08-12-45-21")

In [28]:
# TODO: the error from the average over seed is not computed correctly.
results_lopo = present_results(
    all_results,
    val_method="lnpo",
    remove_xgboost=True,
    remove_chronos_small_from_test=True,
    average_over_seed=True,
)

                                                                                                                                         Seed  \
Aggregator         Dataset   Features                                    Label Name    Model                Resampling Side  Validation
MeanChanAggregator usilaughs ibm-granite/granite-timeseries-patchtsmixer cognitiveload LogisticRegression   None       right LNPO         NaN
None               usilaughs HandcraftedFeatureExtractor                 cognitiveload DummyClassifier      None       right LNPO         NaN
                                                                                       LogisticRegression   None       right LNPO         NaN
                             NoneFeatureExtractor                        cognitiveload CustomKernelSVC      None       right LNPO         NaN
                                                                                       KNeighborsClassifier None       right LNPO         NaN
                                                                                       LogisticRegression   None       right LNPO         NaN

                                                                                                                                        accuracy_score  \
Aggregator         Dataset   Features                                    Label Name    Model                Resampling Side  Validation
MeanChanAggregator usilaughs ibm-granite/granite-timeseries-patchtsmixer cognitiveload LogisticRegression   None       right LNPO          0.70 ± 0.05
None               usilaughs HandcraftedFeatureExtractor                 cognitiveload DummyClassifier      None       right LNPO          0.55 ± 0.00
                                                                                       LogisticRegression   None       right LNPO          0.71 ± 0.05
                             NoneFeatureExtractor                        cognitiveload CustomKernelSVC      None       right LNPO          0.74 ± 0.04
                                                                                       KNeighborsClassifier None       right LNPO          0.71 ± 0.05
                                                                                       LogisticRegression   None       right LNPO          0.75 ± 0.04

                                                                                                                                        balanced_accuracy_score  \
Aggregator         Dataset   Features                                    Label Name    Model                Resampling Side  Validation
MeanChanAggregator usilaughs ibm-granite/granite-timeseries-patchtsmixer cognitiveload LogisticRegression   None       right LNPO                   0.70 ± 0.04
None               usilaughs HandcraftedFeatureExtractor                 cognitiveload DummyClassifier      None       right LNPO                   0.54 ± 0.00
                                                                                       LogisticRegression   None       right LNPO                   0.72 ± 0.04
                             NoneFeatureExtractor                        cognitiveload CustomKernelSVC      None       right LNPO                   0.74 ± 0.04
                                                                                       KNeighborsClassifier None       right LNPO                   0.71 ± 0.05
                                                                                       LogisticRegression   None       right LNPO                   0.75 ± 0.04

                                                                                                                                            f1_score  \
Aggregator         Dataset   Features                                    Label Name    Model                Resampling Side  Validation
MeanChanAggregator usilaughs ibm-granite/granite-timeseries-patchtsmixer cognitiveload LogisticRegression   None       right LNPO        0.68 ± 0.04
None               usilaughs HandcraftedFeatureExtractor                 cognitiveload DummyClassifier      None       right LNPO        0.35 ± 0.00
                                                                                       LogisticRegression   None       right LNPO        0.71 ± 0.04
                             NoneFeatureExtractor                        cognitiveload CustomKernelSVC      None       right LNPO        0.72 ± 0.04
                                                                                       KNeighborsClassifier None       right LNPO        0.69 ± 0.05
                                                                                       LogisticRegression   None       right LNPO        0.73 ± 0.03

                                                                                                                                        matthews_corrcoef  \
Aggregator         Dataset   Features                                    Label Name    Model                Resampling Side  Validation
MeanChanAggregator usilaughs ibm-granite/granite-timeseries-patchtsmixer cognitiveload LogisticRegression   None       right LNPO             0.41 ± 0.09
None               usilaughs HandcraftedFeatureExtractor                 cognitiveload DummyClassifier      None       right LNPO             0.07 ± 0.00
                                                                                       LogisticRegression   None       right LNPO             0.45 ± 0.08
                             NoneFeatureExtractor                        cognitiveload CustomKernelSVC      None       right LNPO             0.49 ± 0.08
                                                                                       KNeighborsClassifier None       right LNPO             0.43 ± 0.09
                                                                                       LogisticRegression   None       right LNPO             0.51 ± 0.08

                                                                                                                                        precision_score  \
Aggregator         Dataset   Features                                    Label Name    Model                Resampling Side  Validation
MeanChanAggregator usilaughs ibm-granite/granite-timeseries-patchtsmixer cognitiveload LogisticRegression   None       right LNPO           0.66 ± 0.07
None               usilaughs HandcraftedFeatureExtractor                 cognitiveload DummyClassifier      None       right LNPO           0.33 ± 0.00
                                                                                       LogisticRegression   None       right LNPO           0.67 ± 0.07
                             NoneFeatureExtractor                        cognitiveload CustomKernelSVC      None       right LNPO           0.71 ± 0.06
                                                                                       KNeighborsClassifier None       right LNPO           0.68 ± 0.06
                                                                                       LogisticRegression   None       right LNPO           0.73 ± 0.07

                                                                                                                                        recall_score  \
Aggregator         Dataset   Features                                    Label Name    Model                Resampling Side  Validation
MeanChanAggregator usilaughs ibm-granite/granite-timeseries-patchtsmixer cognitiveload LogisticRegression   None       right LNPO        0.72 ± 0.05
None               usilaughs HandcraftedFeatureExtractor                 cognitiveload DummyClassifier      None       right LNPO        0.37 ± 0.00
                                                                                       LogisticRegression   None       right LNPO        0.78 ± 0.05
                             NoneFeatureExtractor                        cognitiveload CustomKernelSVC      None       right LNPO        0.75 ± 0.05
                                                                                       KNeighborsClassifier None       right LNPO        0.70 ± 0.06
                                                                                       LogisticRegression   None       right LNPO        0.74 ± 0.05

                                                                                                                                        roc_auc_score
Aggregator         Dataset   Features                                    Label Name    Model                Resampling Side  Validation
MeanChanAggregator usilaughs ibm-granite/granite-timeseries-patchtsmixer cognitiveload LogisticRegression   None       right LNPO         0.70 ± 0.04
None               usilaughs HandcraftedFeatureExtractor                 cognitiveload DummyClassifier      None       right LNPO         0.54 ± 0.00
                                                                                       LogisticRegression   None       right LNPO         0.72 ± 0.04
                             NoneFeatureExtractor                        cognitiveload CustomKernelSVC      None       right LNPO         0.74 ± 0.04
                                                                                       KNeighborsClassifier None       right LNPO         0.71 ± 0.05
                                                                                       LogisticRegression   None       right LNPO         0.75 ± 0.04

Friedman Test accuracy_score: statistic=16.667, pvalue=0.005
Nemenyi post-hoc test

                                                                      CustomKernelSVC  \
                                                                 NoneFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                    1.000000
DummyClassifier      HandcraftedFeatureExtractor                             0.074302
KNeighborsClassifier NoneFeatureExtractor                                    0.999420
LogisticRegression   HandcraftedFeatureExtractor                             0.991626
                     NoneFeatureExtractor                                    0.845079
                     ibm-granite/granite-timeseries-patchtsmixer             0.882097

                                                                             DummyClassifier  \
                                                                 HandcraftedFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                           0.074302
DummyClassifier      HandcraftedFeatureExtractor                                    1.000000
KNeighborsClassifier NoneFeatureExtractor                                           0.168134
LogisticRegression   HandcraftedFeatureExtractor                                    0.280437
                     NoneFeatureExtractor                                           0.001417
                     ibm-granite/granite-timeseries-patchtsmixer                    0.594680

                                                                 KNeighborsClassifier  \
                                                                 NoneFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                    0.999420
DummyClassifier      HandcraftedFeatureExtractor                             0.168134
KNeighborsClassifier NoneFeatureExtractor                                    1.000000
LogisticRegression   HandcraftedFeatureExtractor                             0.999858
                     NoneFeatureExtractor                                    0.650490
                     ibm-granite/granite-timeseries-patchtsmixer             0.973980

                                                                          LogisticRegression  \
                                                                 HandcraftedFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                           0.991626
DummyClassifier      HandcraftedFeatureExtractor                                    0.280437
KNeighborsClassifier NoneFeatureExtractor                                           0.999858
LogisticRegression   HandcraftedFeatureExtractor                                    1.000000
                     NoneFeatureExtractor                                           0.482135
                     ibm-granite/granite-timeseries-patchtsmixer                    0.995925

                                                                                       \
                                                                 NoneFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                    0.845079
DummyClassifier      HandcraftedFeatureExtractor                             0.001417
KNeighborsClassifier NoneFeatureExtractor                                    0.650490
LogisticRegression   HandcraftedFeatureExtractor                             0.482135
                     NoneFeatureExtractor                                    1.000000
                     ibm-granite/granite-timeseries-patchtsmixer             0.201363


                                                                 ibm-granite/granite-timeseries-patchtsmixer
CustomKernelSVC      NoneFeatureExtractor                                                           0.882097
DummyClassifier      HandcraftedFeatureExtractor                                                    0.594680
KNeighborsClassifier NoneFeatureExtractor                                                           0.973980
LogisticRegression   HandcraftedFeatureExtractor                                                    0.995925
                     NoneFeatureExtractor                                                           0.201363
                     ibm-granite/granite-timeseries-patchtsmixer                                    1.000000

Friedman Test balanced_accuracy_score: statistic=16.314, pvalue=0.006
Nemenyi post-hoc test

                                                                      CustomKernelSVC  \
                                                                 NoneFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                    1.000000
DummyClassifier      HandcraftedFeatureExtractor                             0.074302
KNeighborsClassifier NoneFeatureExtractor                                    0.995925
LogisticRegression   HandcraftedFeatureExtractor                             0.995925
                     NoneFeatureExtractor                                    0.845079
                     ibm-granite/granite-timeseries-patchtsmixer             0.913410

                                                                             DummyClassifier  \
                                                                 HandcraftedFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                           0.074302
DummyClassifier      HandcraftedFeatureExtractor                                    1.000000
KNeighborsClassifier NoneFeatureExtractor                                           0.238812
LogisticRegression   HandcraftedFeatureExtractor                                    0.238812
                     NoneFeatureExtractor                                           0.001417
                     ibm-granite/granite-timeseries-patchtsmixer                    0.538193

                                                                 KNeighborsClassifier  \
                                                                 NoneFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                    0.995925
DummyClassifier      HandcraftedFeatureExtractor                             0.238812
KNeighborsClassifier NoneFeatureExtractor                                    1.000000
LogisticRegression   HandcraftedFeatureExtractor                             1.000000
                     NoneFeatureExtractor                                    0.538193
                     ibm-granite/granite-timeseries-patchtsmixer             0.995925

                                                                          LogisticRegression  \
                                                                 HandcraftedFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                           0.995925
DummyClassifier      HandcraftedFeatureExtractor                                    0.238812
KNeighborsClassifier NoneFeatureExtractor                                           1.000000
LogisticRegression   HandcraftedFeatureExtractor                                    1.000000
                     NoneFeatureExtractor                                           0.538193
                     ibm-granite/granite-timeseries-patchtsmixer                    0.995925

                                                                                       \
                                                                 NoneFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                    0.845079
DummyClassifier      HandcraftedFeatureExtractor                             0.001417
KNeighborsClassifier NoneFeatureExtractor                                    0.538193
LogisticRegression   HandcraftedFeatureExtractor                             0.538193
                     NoneFeatureExtractor                                    1.000000
                     ibm-granite/granite-timeseries-patchtsmixer             0.238812


                                                                 ibm-granite/granite-timeseries-patchtsmixer
CustomKernelSVC      NoneFeatureExtractor                                                           0.913410
DummyClassifier      HandcraftedFeatureExtractor                                                    0.538193
KNeighborsClassifier NoneFeatureExtractor                                                           0.995925
LogisticRegression   HandcraftedFeatureExtractor                                                    0.995925
                     NoneFeatureExtractor                                                           0.238812
                     ibm-granite/granite-timeseries-patchtsmixer                                    1.000000

Friedman Test matthews_corrcoef: statistic=16.314, pvalue=0.006
Nemenyi post-hoc test

                                                                      CustomKernelSVC  \
                                                                 NoneFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                    1.000000
DummyClassifier      HandcraftedFeatureExtractor                             0.074302
KNeighborsClassifier NoneFeatureExtractor                                    0.995925
LogisticRegression   HandcraftedFeatureExtractor                             0.995925
                     NoneFeatureExtractor                                    0.845079
                     ibm-granite/granite-timeseries-patchtsmixer             0.913410

                                                                             DummyClassifier  \
                                                                 HandcraftedFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                           0.074302
DummyClassifier      HandcraftedFeatureExtractor                                    1.000000
KNeighborsClassifier NoneFeatureExtractor                                           0.238812
LogisticRegression   HandcraftedFeatureExtractor                                    0.238812
                     NoneFeatureExtractor                                           0.001417
                     ibm-granite/granite-timeseries-patchtsmixer                    0.538193

                                                                 KNeighborsClassifier  \
                                                                 NoneFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                    0.995925
DummyClassifier      HandcraftedFeatureExtractor                             0.238812
KNeighborsClassifier NoneFeatureExtractor                                    1.000000
LogisticRegression   HandcraftedFeatureExtractor                             1.000000
                     NoneFeatureExtractor                                    0.538193
                     ibm-granite/granite-timeseries-patchtsmixer             0.995925

                                                                          LogisticRegression  \
                                                                 HandcraftedFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                           0.995925
DummyClassifier      HandcraftedFeatureExtractor                                    0.238812
KNeighborsClassifier NoneFeatureExtractor                                           1.000000
LogisticRegression   HandcraftedFeatureExtractor                                    1.000000
                     NoneFeatureExtractor                                           0.538193
                     ibm-granite/granite-timeseries-patchtsmixer                    0.995925

                                                                                       \
                                                                 NoneFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                    0.845079
DummyClassifier      HandcraftedFeatureExtractor                             0.001417
KNeighborsClassifier NoneFeatureExtractor                                    0.538193
LogisticRegression   HandcraftedFeatureExtractor                             0.538193
                     NoneFeatureExtractor                                    1.000000
                     ibm-granite/granite-timeseries-patchtsmixer             0.238812


                                                                 ibm-granite/granite-timeseries-patchtsmixer
CustomKernelSVC      NoneFeatureExtractor                                                           0.913410
DummyClassifier      HandcraftedFeatureExtractor                                                    0.538193
KNeighborsClassifier NoneFeatureExtractor                                                           0.995925
LogisticRegression   HandcraftedFeatureExtractor                                                    0.995925
                     NoneFeatureExtractor                                                           0.238812
                     ibm-granite/granite-timeseries-patchtsmixer                                    1.000000

Friedman Test f1_score: statistic=16.543, pvalue=0.005
Nemenyi post-hoc test

                                                                      CustomKernelSVC  \
                                                                 NoneFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                    1.000000
DummyClassifier      HandcraftedFeatureExtractor                             0.113891
KNeighborsClassifier NoneFeatureExtractor                                    0.999981
LogisticRegression   HandcraftedFeatureExtractor                             0.999981
                     NoneFeatureExtractor                                    0.755551
                     ibm-granite/granite-timeseries-patchtsmixer             0.913410

                                                                             DummyClassifier  \
                                                                 HandcraftedFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                           0.113891
DummyClassifier      HandcraftedFeatureExtractor                                    1.000000
KNeighborsClassifier NoneFeatureExtractor                                           0.168134
LogisticRegression   HandcraftedFeatureExtractor                                    0.168134
                     NoneFeatureExtractor                                           0.001417
                     ibm-granite/granite-timeseries-patchtsmixer                    0.650490

                                                                 KNeighborsClassifier  \
                                                                 NoneFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                    0.999981
DummyClassifier      HandcraftedFeatureExtractor                             0.168134
KNeighborsClassifier NoneFeatureExtractor                                    1.000000
LogisticRegression   HandcraftedFeatureExtractor                             1.000000
                     NoneFeatureExtractor                                    0.650490
                     ibm-granite/granite-timeseries-patchtsmixer             0.958997

                                                                          LogisticRegression  \
                                                                 HandcraftedFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                           0.999981
DummyClassifier      HandcraftedFeatureExtractor                                    0.168134
KNeighborsClassifier NoneFeatureExtractor                                           1.000000
LogisticRegression   HandcraftedFeatureExtractor                                    1.000000
                     NoneFeatureExtractor                                           0.650490
                     ibm-granite/granite-timeseries-patchtsmixer                    0.958997

                                                                                       \
                                                                 NoneFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                    0.755551
DummyClassifier      HandcraftedFeatureExtractor                             0.001417
KNeighborsClassifier NoneFeatureExtractor                                    0.650490
LogisticRegression   HandcraftedFeatureExtractor                             0.650490
                     NoneFeatureExtractor                                    1.000000
                     ibm-granite/granite-timeseries-patchtsmixer             0.168134


                                                                 ibm-granite/granite-timeseries-patchtsmixer
CustomKernelSVC      NoneFeatureExtractor                                                           0.913410
DummyClassifier      HandcraftedFeatureExtractor                                                    0.650490
KNeighborsClassifier NoneFeatureExtractor                                                           0.958997
LogisticRegression   HandcraftedFeatureExtractor                                                    0.958997
                     NoneFeatureExtractor                                                           0.168134
                     ibm-granite/granite-timeseries-patchtsmixer                                    1.000000

Friedman Test precision_score: statistic=16.839, pvalue=0.005
Nemenyi post-hoc test

                                                                      CustomKernelSVC  \
                                                                 NoneFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                    1.000000
DummyClassifier      HandcraftedFeatureExtractor                             0.074302
KNeighborsClassifier NoneFeatureExtractor                                    0.999981
LogisticRegression   HandcraftedFeatureExtractor                             0.938967
                     NoneFeatureExtractor                                    0.845079
                     ibm-granite/granite-timeseries-patchtsmixer             0.938967

                                                                             DummyClassifier  \
                                                                 HandcraftedFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                           0.074302
DummyClassifier      HandcraftedFeatureExtractor                                    1.000000
KNeighborsClassifier NoneFeatureExtractor                                           0.113891
LogisticRegression   HandcraftedFeatureExtractor                                    0.482135
                     NoneFeatureExtractor                                           0.001417
                     ibm-granite/granite-timeseries-patchtsmixer                    0.482135

                                                                 KNeighborsClassifier  \
                                                                 NoneFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                    0.999981
DummyClassifier      HandcraftedFeatureExtractor                             0.113891
KNeighborsClassifier NoneFeatureExtractor                                    1.000000
LogisticRegression   HandcraftedFeatureExtractor                             0.973980
                     NoneFeatureExtractor                                    0.755551
                     ibm-granite/granite-timeseries-patchtsmixer             0.973980

                                                                          LogisticRegression  \
                                                                 HandcraftedFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                           0.938967
DummyClassifier      HandcraftedFeatureExtractor                                    0.482135
KNeighborsClassifier NoneFeatureExtractor                                           0.973980
LogisticRegression   HandcraftedFeatureExtractor                                    1.000000
                     NoneFeatureExtractor                                           0.280437
                     ibm-granite/granite-timeseries-patchtsmixer                    1.000000

                                                                                       \
                                                                 NoneFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                    0.845079
DummyClassifier      HandcraftedFeatureExtractor                             0.001417
KNeighborsClassifier NoneFeatureExtractor                                    0.755551
LogisticRegression   HandcraftedFeatureExtractor                             0.280437
                     NoneFeatureExtractor                                    1.000000
                     ibm-granite/granite-timeseries-patchtsmixer             0.280437


                                                                 ibm-granite/granite-timeseries-patchtsmixer
CustomKernelSVC      NoneFeatureExtractor                                                           0.938967
DummyClassifier      HandcraftedFeatureExtractor                                                    0.482135
KNeighborsClassifier NoneFeatureExtractor                                                           0.973980
LogisticRegression   HandcraftedFeatureExtractor                                                    1.000000
                     NoneFeatureExtractor                                                           0.280437
                     ibm-granite/granite-timeseries-patchtsmixer                                    1.000000

Friedman Test recall_score: statistic=15.585, pvalue=0.008
Nemenyi post-hoc test

                                                                      CustomKernelSVC  \
                                                                 NoneFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                    1.000000
DummyClassifier      HandcraftedFeatureExtractor                             0.139040
KNeighborsClassifier NoneFeatureExtractor                                    0.995925
LogisticRegression   HandcraftedFeatureExtractor                             0.845079
                     NoneFeatureExtractor                                    0.998290
                     ibm-granite/granite-timeseries-patchtsmixer             0.984591

                                                                             DummyClassifier  \
                                                                 HandcraftedFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                           0.139040
DummyClassifier      HandcraftedFeatureExtractor                                    1.000000
KNeighborsClassifier NoneFeatureExtractor                                           0.375252
LogisticRegression   HandcraftedFeatureExtractor                                    0.003789
                     NoneFeatureExtractor                                           0.046736
                     ibm-granite/granite-timeseries-patchtsmixer                    0.482135

                                                                 KNeighborsClassifier  \
                                                                 NoneFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                    0.995925
DummyClassifier      HandcraftedFeatureExtractor                             0.375252
KNeighborsClassifier NoneFeatureExtractor                                    1.000000
LogisticRegression   HandcraftedFeatureExtractor                             0.538193
                     NoneFeatureExtractor                                    0.938967
                     ibm-granite/granite-timeseries-patchtsmixer             0.999981

                                                                          LogisticRegression  \
                                                                 HandcraftedFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                           0.845079
DummyClassifier      HandcraftedFeatureExtractor                                    0.003789
KNeighborsClassifier NoneFeatureExtractor                                           0.538193
LogisticRegression   HandcraftedFeatureExtractor                                    1.000000
                     NoneFeatureExtractor                                           0.973980
                     ibm-granite/granite-timeseries-patchtsmixer                    0.427525

                                                                                       \
                                                                 NoneFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                    0.998290
DummyClassifier      HandcraftedFeatureExtractor                             0.046736
KNeighborsClassifier NoneFeatureExtractor                                    0.938967
LogisticRegression   HandcraftedFeatureExtractor                             0.973980
                     NoneFeatureExtractor                                    1.000000
                     ibm-granite/granite-timeseries-patchtsmixer             0.882097


                                                                 ibm-granite/granite-timeseries-patchtsmixer
CustomKernelSVC      NoneFeatureExtractor                                                           0.984591
DummyClassifier      HandcraftedFeatureExtractor                                                    0.482135
KNeighborsClassifier NoneFeatureExtractor                                                           0.999981
LogisticRegression   HandcraftedFeatureExtractor                                                    0.427525
                     NoneFeatureExtractor                                                           0.882097
                     ibm-granite/granite-timeseries-patchtsmixer                                    1.000000

Friedman Test roc_auc_score: statistic=16.314, pvalue=0.006
Nemenyi post-hoc test

                                                                      CustomKernelSVC  \
                                                                 NoneFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                    1.000000
DummyClassifier      HandcraftedFeatureExtractor                             0.074302
KNeighborsClassifier NoneFeatureExtractor                                    0.995925
LogisticRegression   HandcraftedFeatureExtractor                             0.995925
                     NoneFeatureExtractor                                    0.845079
                     ibm-granite/granite-timeseries-patchtsmixer             0.913410

                                                                             DummyClassifier  \
                                                                 HandcraftedFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                           0.074302
DummyClassifier      HandcraftedFeatureExtractor                                    1.000000
KNeighborsClassifier NoneFeatureExtractor                                           0.238812
LogisticRegression   HandcraftedFeatureExtractor                                    0.238812
                     NoneFeatureExtractor                                           0.001417
                     ibm-granite/granite-timeseries-patchtsmixer                    0.538193

                                                                 KNeighborsClassifier  \
                                                                 NoneFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                    0.995925
DummyClassifier      HandcraftedFeatureExtractor                             0.238812
KNeighborsClassifier NoneFeatureExtractor                                    1.000000
LogisticRegression   HandcraftedFeatureExtractor                             1.000000
                     NoneFeatureExtractor                                    0.538193
                     ibm-granite/granite-timeseries-patchtsmixer             0.995925

                                                                          LogisticRegression  \
                                                                 HandcraftedFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                           0.995925
DummyClassifier      HandcraftedFeatureExtractor                                    0.238812
KNeighborsClassifier NoneFeatureExtractor                                           1.000000
LogisticRegression   HandcraftedFeatureExtractor                                    1.000000
                     NoneFeatureExtractor                                           0.538193
                     ibm-granite/granite-timeseries-patchtsmixer                    0.995925

                                                                                       \
                                                                 NoneFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                    0.845079
DummyClassifier      HandcraftedFeatureExtractor                             0.001417
KNeighborsClassifier NoneFeatureExtractor                                    0.538193
LogisticRegression   HandcraftedFeatureExtractor                             0.538193
                     NoneFeatureExtractor                                    1.000000
                     ibm-granite/granite-timeseries-patchtsmixer             0.238812


                                                                 ibm-granite/granite-timeseries-patchtsmixer
CustomKernelSVC      NoneFeatureExtractor                                                           0.913410
DummyClassifier      HandcraftedFeatureExtractor                                                    0.538193
KNeighborsClassifier NoneFeatureExtractor                                                           0.995925
LogisticRegression   HandcraftedFeatureExtractor                                                    0.995925
                     NoneFeatureExtractor                                                           0.238812
                     ibm-granite/granite-timeseries-patchtsmixer                                    1.000000

In [29]:
# TODO: the error from the average over seed is not computed correctly.
results_lopo = present_results(
    all_results,
    val_method="tacv",
    remove_xgboost=True,
    remove_chronos_small_from_test=True,
    average_over_seed=True,
)

                                                                                                                                         Seed  \
Aggregator         Dataset   Features                                    Label Name    Model                Resampling Side  Validation
MeanChanAggregator usilaughs ibm-granite/granite-timeseries-patchtsmixer cognitiveload LogisticRegression   None       right TACV         NaN
None               usilaughs HandcraftedFeatureExtractor                 cognitiveload DummyClassifier      None       right TACV         NaN
                                                                                       LogisticRegression   None       right TACV         NaN
                             NoneFeatureExtractor                        cognitiveload CustomKernelSVC      None       right TACV         NaN
                                                                                       KNeighborsClassifier None       right TACV         NaN
                                                                                       LogisticRegression   None       right TACV         NaN

                                                                                                                                        accuracy_score  \
Aggregator         Dataset   Features                                    Label Name    Model                Resampling Side  Validation
MeanChanAggregator usilaughs ibm-granite/granite-timeseries-patchtsmixer cognitiveload LogisticRegression   None       right TACV          0.72 ± 0.07
None               usilaughs HandcraftedFeatureExtractor                 cognitiveload DummyClassifier      None       right TACV          0.61 ± 0.00
                                                                                       LogisticRegression   None       right TACV          0.76 ± 0.04
                             NoneFeatureExtractor                        cognitiveload CustomKernelSVC      None       right TACV          0.80 ± 0.07
                                                                                       KNeighborsClassifier None       right TACV          0.81 ± 0.04
                                                                                       LogisticRegression   None       right TACV          0.81 ± 0.06

                                                                                                                                        balanced_accuracy_score  \
Aggregator         Dataset   Features                                    Label Name    Model                Resampling Side  Validation
MeanChanAggregator usilaughs ibm-granite/granite-timeseries-patchtsmixer cognitiveload LogisticRegression   None       right TACV                   0.73 ± 0.07
None               usilaughs HandcraftedFeatureExtractor                 cognitiveload DummyClassifier      None       right TACV                   0.61 ± 0.00
                                                                                       LogisticRegression   None       right TACV                   0.78 ± 0.04
                             NoneFeatureExtractor                        cognitiveload CustomKernelSVC      None       right TACV                   0.80 ± 0.07
                                                                                       KNeighborsClassifier None       right TACV                   0.81 ± 0.04
                                                                                       LogisticRegression   None       right TACV                   0.81 ± 0.05

                                                                                                                                            f1_score  \
Aggregator         Dataset   Features                                    Label Name    Model                Resampling Side  Validation
MeanChanAggregator usilaughs ibm-granite/granite-timeseries-patchtsmixer cognitiveload LogisticRegression   None       right TACV        0.72 ± 0.07
None               usilaughs HandcraftedFeatureExtractor                 cognitiveload DummyClassifier      None       right TACV        0.56 ± 0.00
                                                                                       LogisticRegression   None       right TACV        0.78 ± 0.03
                             NoneFeatureExtractor                        cognitiveload CustomKernelSVC      None       right TACV        0.78 ± 0.07
                                                                                       KNeighborsClassifier None       right TACV        0.80 ± 0.04
                                                                                       LogisticRegression   None       right TACV        0.80 ± 0.05

                                                                                                                                        matthews_corrcoef  \
Aggregator         Dataset   Features                                    Label Name    Model                Resampling Side  Validation
MeanChanAggregator usilaughs ibm-granite/granite-timeseries-patchtsmixer cognitiveload LogisticRegression   None       right TACV             0.47 ± 0.13
None               usilaughs HandcraftedFeatureExtractor                 cognitiveload DummyClassifier      None       right TACV             0.22 ± 0.00
                                                                                       LogisticRegression   None       right TACV             0.57 ± 0.07
                             NoneFeatureExtractor                        cognitiveload CustomKernelSVC      None       right TACV             0.61 ± 0.14
                                                                                       KNeighborsClassifier None       right TACV             0.63 ± 0.08
                                                                                       LogisticRegression   None       right TACV             0.63 ± 0.11

                                                                                                                                        precision_score  \
Aggregator         Dataset   Features                                    Label Name    Model                Resampling Side  Validation
MeanChanAggregator usilaughs ibm-granite/granite-timeseries-patchtsmixer cognitiveload LogisticRegression   None       right TACV           0.66 ± 0.06
None               usilaughs HandcraftedFeatureExtractor                 cognitiveload DummyClassifier      None       right TACV           0.57 ± 0.00
                                                                                       LogisticRegression   None       right TACV           0.69 ± 0.04
                             NoneFeatureExtractor                        cognitiveload CustomKernelSVC      None       right TACV           0.76 ± 0.07
                                                                                       KNeighborsClassifier None       right TACV           0.76 ± 0.05
                                                                                       LogisticRegression   None       right TACV           0.77 ± 0.07

                                                                                                                                        recall_score  \
Aggregator         Dataset   Features                                    Label Name    Model                Resampling Side  Validation
MeanChanAggregator usilaughs ibm-granite/granite-timeseries-patchtsmixer cognitiveload LogisticRegression   None       right TACV        0.80 ± 0.09
None               usilaughs HandcraftedFeatureExtractor                 cognitiveload DummyClassifier      None       right TACV        0.55 ± 0.00
                                                                                       LogisticRegression   None       right TACV        0.91 ± 0.03
                             NoneFeatureExtractor                        cognitiveload CustomKernelSVC      None       right TACV        0.82 ± 0.08
                                                                                       KNeighborsClassifier None       right TACV        0.85 ± 0.04
                                                                                       LogisticRegression   None       right TACV        0.83 ± 0.07

                                                                                                                                        roc_auc_score
Aggregator         Dataset   Features                                    Label Name    Model                Resampling Side  Validation
MeanChanAggregator usilaughs ibm-granite/granite-timeseries-patchtsmixer cognitiveload LogisticRegression   None       right TACV         0.73 ± 0.07
None               usilaughs HandcraftedFeatureExtractor                 cognitiveload DummyClassifier      None       right TACV         0.61 ± 0.00
                                                                                       LogisticRegression   None       right TACV         0.78 ± 0.04
                             NoneFeatureExtractor                        cognitiveload CustomKernelSVC      None       right TACV         0.80 ± 0.07
                                                                                       KNeighborsClassifier None       right TACV         0.81 ± 0.04
                                                                                       LogisticRegression   None       right TACV         0.81 ± 0.05

Friedman Test accuracy_score: statistic=11.935, pvalue=0.036
Nemenyi post-hoc test

                                                                      CustomKernelSVC  \
                                                                 NoneFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                    1.000000
DummyClassifier      HandcraftedFeatureExtractor                             0.427525
KNeighborsClassifier NoneFeatureExtractor                                    0.991626
LogisticRegression   HandcraftedFeatureExtractor                             0.991626
                     NoneFeatureExtractor                                    0.973980
                     ibm-granite/granite-timeseries-patchtsmixer             0.704482

                                                                             DummyClassifier  \
                                                                 HandcraftedFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                           0.427525
DummyClassifier      HandcraftedFeatureExtractor                                    1.000000
KNeighborsClassifier NoneFeatureExtractor                                           0.139040
LogisticRegression   HandcraftedFeatureExtractor                                    0.802694
                     NoneFeatureExtractor                                           0.092418
                     ibm-granite/granite-timeseries-patchtsmixer                    0.998290

                                                                 KNeighborsClassifier  \
                                                                 NoneFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                    0.991626
DummyClassifier      HandcraftedFeatureExtractor                             0.139040
KNeighborsClassifier NoneFeatureExtractor                                    1.000000
LogisticRegression   HandcraftedFeatureExtractor                             0.845079
                     NoneFeatureExtractor                                    0.999981
                     ibm-granite/granite-timeseries-patchtsmixer             0.326040

                                                                          LogisticRegression  \
                                                                 HandcraftedFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                           0.991626
DummyClassifier      HandcraftedFeatureExtractor                                    0.802694
KNeighborsClassifier NoneFeatureExtractor                                           0.845079
LogisticRegression   HandcraftedFeatureExtractor                                    1.000000
                     NoneFeatureExtractor                                           0.755551
                     ibm-granite/granite-timeseries-patchtsmixer                    0.958997

                                                                                       \
                                                                 NoneFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                    0.973980
DummyClassifier      HandcraftedFeatureExtractor                             0.092418
KNeighborsClassifier NoneFeatureExtractor                                    0.999981
LogisticRegression   HandcraftedFeatureExtractor                             0.755551
                     NoneFeatureExtractor                                    1.000000
                     ibm-granite/granite-timeseries-patchtsmixer             0.238812


                                                                 ibm-granite/granite-timeseries-patchtsmixer
CustomKernelSVC      NoneFeatureExtractor                                                           0.704482
DummyClassifier      HandcraftedFeatureExtractor                                                    0.998290
KNeighborsClassifier NoneFeatureExtractor                                                           0.326040
LogisticRegression   HandcraftedFeatureExtractor                                                    0.958997
                     NoneFeatureExtractor                                                           0.238812
                     ibm-granite/granite-timeseries-patchtsmixer                                    1.000000

Friedman Test balanced_accuracy_score: statistic=11.221, pvalue=0.047
Nemenyi post-hoc test

                                                                      CustomKernelSVC  \
                                                                 NoneFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                    1.000000
DummyClassifier      HandcraftedFeatureExtractor                             0.375252
KNeighborsClassifier NoneFeatureExtractor                                    0.991626
LogisticRegression   HandcraftedFeatureExtractor                             0.999999
                     NoneFeatureExtractor                                    0.984591
                     ibm-granite/granite-timeseries-patchtsmixer             0.802694

                                                                             DummyClassifier  \
                                                                 HandcraftedFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                           0.375252
DummyClassifier      HandcraftedFeatureExtractor                                    1.000000
KNeighborsClassifier NoneFeatureExtractor                                           0.113891
LogisticRegression   HandcraftedFeatureExtractor                                    0.427525
                     NoneFeatureExtractor                                           0.092418
                     ibm-granite/granite-timeseries-patchtsmixer                    0.984591

                                                                 KNeighborsClassifier  \
                                                                 NoneFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                    0.991626
DummyClassifier      HandcraftedFeatureExtractor                             0.113891
KNeighborsClassifier NoneFeatureExtractor                                    1.000000
LogisticRegression   HandcraftedFeatureExtractor                             0.984591
                     NoneFeatureExtractor                                    0.999999
                     ibm-granite/granite-timeseries-patchtsmixer             0.427525

                                                                          LogisticRegression  \
                                                                 HandcraftedFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                           0.999999
DummyClassifier      HandcraftedFeatureExtractor                                    0.427525
KNeighborsClassifier NoneFeatureExtractor                                           0.984591
LogisticRegression   HandcraftedFeatureExtractor                                    1.000000
                     NoneFeatureExtractor                                           0.973980
                     ibm-granite/granite-timeseries-patchtsmixer                    0.845079

                                                                                       \
                                                                 NoneFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                    0.984591
DummyClassifier      HandcraftedFeatureExtractor                             0.092418
KNeighborsClassifier NoneFeatureExtractor                                    0.999999
LogisticRegression   HandcraftedFeatureExtractor                             0.973980
                     NoneFeatureExtractor                                    1.000000
                     ibm-granite/granite-timeseries-patchtsmixer             0.375252


                                                                 ibm-granite/granite-timeseries-patchtsmixer
CustomKernelSVC      NoneFeatureExtractor                                                           0.802694
DummyClassifier      HandcraftedFeatureExtractor                                                    0.984591
KNeighborsClassifier NoneFeatureExtractor                                                           0.427525
LogisticRegression   HandcraftedFeatureExtractor                                                    0.845079
                     NoneFeatureExtractor                                                           0.375252
                     ibm-granite/granite-timeseries-patchtsmixer                                    1.000000

Friedman Test matthews_corrcoef: statistic=10.954, pvalue=0.052
Nemenyi post-hoc test

                                                                      CustomKernelSVC  \
                                                                 NoneFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                    1.000000
DummyClassifier      HandcraftedFeatureExtractor                             0.375252
KNeighborsClassifier NoneFeatureExtractor                                    0.995925
LogisticRegression   HandcraftedFeatureExtractor                             1.000000
                     NoneFeatureExtractor                                    0.984591
                     ibm-granite/granite-timeseries-patchtsmixer             0.802694

                                                                             DummyClassifier  \
                                                                 HandcraftedFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                           0.375252
DummyClassifier      HandcraftedFeatureExtractor                                    1.000000
KNeighborsClassifier NoneFeatureExtractor                                           0.139040
LogisticRegression   HandcraftedFeatureExtractor                                    0.375252
                     NoneFeatureExtractor                                           0.092418
                     ibm-granite/granite-timeseries-patchtsmixer                    0.984591

                                                                 KNeighborsClassifier  \
                                                                 NoneFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                    0.995925
DummyClassifier      HandcraftedFeatureExtractor                             0.139040
KNeighborsClassifier NoneFeatureExtractor                                    1.000000
LogisticRegression   HandcraftedFeatureExtractor                             0.995925
                     NoneFeatureExtractor                                    0.999981
                     ibm-granite/granite-timeseries-patchtsmixer             0.482135

                                                                          LogisticRegression  \
                                                                 HandcraftedFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                           1.000000
DummyClassifier      HandcraftedFeatureExtractor                                    0.375252
KNeighborsClassifier NoneFeatureExtractor                                           0.995925
LogisticRegression   HandcraftedFeatureExtractor                                    1.000000
                     NoneFeatureExtractor                                           0.984591
                     ibm-granite/granite-timeseries-patchtsmixer                    0.802694

                                                                                       \
                                                                 NoneFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                    0.984591
DummyClassifier      HandcraftedFeatureExtractor                             0.092418
KNeighborsClassifier NoneFeatureExtractor                                    0.999981
LogisticRegression   HandcraftedFeatureExtractor                             0.984591
                     NoneFeatureExtractor                                    1.000000
                     ibm-granite/granite-timeseries-patchtsmixer             0.375252


                                                                 ibm-granite/granite-timeseries-patchtsmixer
CustomKernelSVC      NoneFeatureExtractor                                                           0.802694
DummyClassifier      HandcraftedFeatureExtractor                                                    0.984591
KNeighborsClassifier NoneFeatureExtractor                                                           0.482135
LogisticRegression   HandcraftedFeatureExtractor                                                    0.802694
                     NoneFeatureExtractor                                                           0.375252
                     ibm-granite/granite-timeseries-patchtsmixer                                    1.000000

Friedman Test f1_score: statistic=13.786, pvalue=0.017
Nemenyi post-hoc test

                                                                      CustomKernelSVC  \
                                                                 NoneFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                    1.000000
DummyClassifier      HandcraftedFeatureExtractor                             0.092418
KNeighborsClassifier NoneFeatureExtractor                                    0.999981
LogisticRegression   HandcraftedFeatureExtractor                             1.000000
                     NoneFeatureExtractor                                    0.995925
                     ibm-granite/granite-timeseries-patchtsmixer             0.882097

                                                                             DummyClassifier  \
                                                                 HandcraftedFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                           0.092418
DummyClassifier      HandcraftedFeatureExtractor                                    1.000000
KNeighborsClassifier NoneFeatureExtractor                                           0.059195
LogisticRegression   HandcraftedFeatureExtractor                                    0.092418
                     NoneFeatureExtractor                                           0.021820
                     ibm-granite/granite-timeseries-patchtsmixer                    0.650490

                                                                 KNeighborsClassifier  \
                                                                 NoneFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                    0.999981
DummyClassifier      HandcraftedFeatureExtractor                             0.059195
KNeighborsClassifier NoneFeatureExtractor                                    1.000000
LogisticRegression   HandcraftedFeatureExtractor                             0.999981
                     NoneFeatureExtractor                                    0.999420
                     ibm-granite/granite-timeseries-patchtsmixer             0.802694

                                                                          LogisticRegression  \
                                                                 HandcraftedFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                           1.000000
DummyClassifier      HandcraftedFeatureExtractor                                    0.092418
KNeighborsClassifier NoneFeatureExtractor                                           0.999981
LogisticRegression   HandcraftedFeatureExtractor                                    1.000000
                     NoneFeatureExtractor                                           0.995925
                     ibm-granite/granite-timeseries-patchtsmixer                    0.882097

                                                                                       \
                                                                 NoneFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                    0.995925
DummyClassifier      HandcraftedFeatureExtractor                             0.021820
KNeighborsClassifier NoneFeatureExtractor                                    0.999420
LogisticRegression   HandcraftedFeatureExtractor                             0.995925
                     NoneFeatureExtractor                                    1.000000
                     ibm-granite/granite-timeseries-patchtsmixer             0.594680


                                                                 ibm-granite/granite-timeseries-patchtsmixer
CustomKernelSVC      NoneFeatureExtractor                                                           0.882097
DummyClassifier      HandcraftedFeatureExtractor                                                    0.650490
KNeighborsClassifier NoneFeatureExtractor                                                           0.802694
LogisticRegression   HandcraftedFeatureExtractor                                                    0.882097
                     NoneFeatureExtractor                                                           0.594680
                     ibm-granite/granite-timeseries-patchtsmixer                                    1.000000

Friedman Test precision_score: statistic=15.925, pvalue=0.007
Nemenyi post-hoc test

                                                                      CustomKernelSVC  \
                                                                 NoneFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                    1.000000
DummyClassifier      HandcraftedFeatureExtractor                             0.280437
KNeighborsClassifier NoneFeatureExtractor                                    0.999420
LogisticRegression   HandcraftedFeatureExtractor                             0.538193
                     NoneFeatureExtractor                                    0.995925
                     ibm-granite/granite-timeseries-patchtsmixer             0.280437

                                                                             DummyClassifier  \
                                                                 HandcraftedFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                           0.280437
DummyClassifier      HandcraftedFeatureExtractor                                    1.000000
KNeighborsClassifier NoneFeatureExtractor                                           0.139040
LogisticRegression   HandcraftedFeatureExtractor                                    0.998290
                     NoneFeatureExtractor                                           0.092418
                     ibm-granite/granite-timeseries-patchtsmixer                    1.000000

                                                                 KNeighborsClassifier  \
                                                                 NoneFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                    0.999420
DummyClassifier      HandcraftedFeatureExtractor                             0.139040
KNeighborsClassifier NoneFeatureExtractor                                    1.000000
LogisticRegression   HandcraftedFeatureExtractor                             0.326040
                     NoneFeatureExtractor                                    0.999981
                     ibm-granite/granite-timeseries-patchtsmixer             0.139040

                                                                          LogisticRegression  \
                                                                 HandcraftedFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                           0.538193
DummyClassifier      HandcraftedFeatureExtractor                                    0.998290
KNeighborsClassifier NoneFeatureExtractor                                           0.326040
LogisticRegression   HandcraftedFeatureExtractor                                    1.000000
                     NoneFeatureExtractor                                           0.238812
                     ibm-granite/granite-timeseries-patchtsmixer                    0.998290

                                                                                       \
                                                                 NoneFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                    0.995925
DummyClassifier      HandcraftedFeatureExtractor                             0.092418
KNeighborsClassifier NoneFeatureExtractor                                    0.999981
LogisticRegression   HandcraftedFeatureExtractor                             0.238812
                     NoneFeatureExtractor                                    1.000000
                     ibm-granite/granite-timeseries-patchtsmixer             0.092418


                                                                 ibm-granite/granite-timeseries-patchtsmixer
CustomKernelSVC      NoneFeatureExtractor                                                           0.280437
DummyClassifier      HandcraftedFeatureExtractor                                                    1.000000
KNeighborsClassifier NoneFeatureExtractor                                                           0.139040
LogisticRegression   HandcraftedFeatureExtractor                                                    0.998290
                     NoneFeatureExtractor                                                           0.092418
                     ibm-granite/granite-timeseries-patchtsmixer                                    1.000000

Friedman Test recall_score: statistic=13.987, pvalue=0.016
Nemenyi post-hoc test

                                                                      CustomKernelSVC  \
                                                                 NoneFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                    1.000000
DummyClassifier      HandcraftedFeatureExtractor                             0.326040
KNeighborsClassifier NoneFeatureExtractor                                    0.995925
LogisticRegression   HandcraftedFeatureExtractor                             0.845079
                     NoneFeatureExtractor                                    0.973980
                     ibm-granite/granite-timeseries-patchtsmixer             0.999999

                                                                             DummyClassifier  \
                                                                 HandcraftedFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                           0.326040
DummyClassifier      HandcraftedFeatureExtractor                                    1.000000
KNeighborsClassifier NoneFeatureExtractor                                           0.113891
LogisticRegression   HandcraftedFeatureExtractor                                    0.016639
                     NoneFeatureExtractor                                           0.059195
                     ibm-granite/granite-timeseries-patchtsmixer                    0.280437

                                                                 KNeighborsClassifier  \
                                                                 NoneFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                    0.995925
DummyClassifier      HandcraftedFeatureExtractor                             0.113891
KNeighborsClassifier NoneFeatureExtractor                                    1.000000
LogisticRegression   HandcraftedFeatureExtractor                             0.984591
                     NoneFeatureExtractor                                    0.999858
                     ibm-granite/granite-timeseries-patchtsmixer             0.998290

                                                                          LogisticRegression  \
                                                                 HandcraftedFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                           0.845079
DummyClassifier      HandcraftedFeatureExtractor                                    0.016639
KNeighborsClassifier NoneFeatureExtractor                                           0.984591
LogisticRegression   HandcraftedFeatureExtractor                                    1.000000
                     NoneFeatureExtractor                                           0.998290
                     ibm-granite/granite-timeseries-patchtsmixer                    0.882097

                                                                                       \
                                                                 NoneFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                    0.973980
DummyClassifier      HandcraftedFeatureExtractor                             0.059195
KNeighborsClassifier NoneFeatureExtractor                                    0.999858
LogisticRegression   HandcraftedFeatureExtractor                             0.998290
                     NoneFeatureExtractor                                    1.000000
                     ibm-granite/granite-timeseries-patchtsmixer             0.984591


                                                                 ibm-granite/granite-timeseries-patchtsmixer
CustomKernelSVC      NoneFeatureExtractor                                                           0.999999
DummyClassifier      HandcraftedFeatureExtractor                                                    0.280437
KNeighborsClassifier NoneFeatureExtractor                                                           0.998290
LogisticRegression   HandcraftedFeatureExtractor                                                    0.882097
                     NoneFeatureExtractor                                                           0.984591
                     ibm-granite/granite-timeseries-patchtsmixer                                    1.000000

Friedman Test roc_auc_score: statistic=11.221, pvalue=0.047
Nemenyi post-hoc test

                                                                      CustomKernelSVC  \
                                                                 NoneFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                    1.000000
DummyClassifier      HandcraftedFeatureExtractor                             0.375252
KNeighborsClassifier NoneFeatureExtractor                                    0.991626
LogisticRegression   HandcraftedFeatureExtractor                             0.999999
                     NoneFeatureExtractor                                    0.984591
                     ibm-granite/granite-timeseries-patchtsmixer             0.802694

                                                                             DummyClassifier  \
                                                                 HandcraftedFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                           0.375252
DummyClassifier      HandcraftedFeatureExtractor                                    1.000000
KNeighborsClassifier NoneFeatureExtractor                                           0.113891
LogisticRegression   HandcraftedFeatureExtractor                                    0.427525
                     NoneFeatureExtractor                                           0.092418
                     ibm-granite/granite-timeseries-patchtsmixer                    0.984591

                                                                 KNeighborsClassifier  \
                                                                 NoneFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                    0.991626
DummyClassifier      HandcraftedFeatureExtractor                             0.113891
KNeighborsClassifier NoneFeatureExtractor                                    1.000000
LogisticRegression   HandcraftedFeatureExtractor                             0.984591
                     NoneFeatureExtractor                                    0.999999
                     ibm-granite/granite-timeseries-patchtsmixer             0.427525

                                                                          LogisticRegression  \
                                                                 HandcraftedFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                           0.999999
DummyClassifier      HandcraftedFeatureExtractor                                    0.427525
KNeighborsClassifier NoneFeatureExtractor                                           0.984591
LogisticRegression   HandcraftedFeatureExtractor                                    1.000000
                     NoneFeatureExtractor                                           0.973980
                     ibm-granite/granite-timeseries-patchtsmixer                    0.845079

                                                                                       \
                                                                 NoneFeatureExtractor
CustomKernelSVC      NoneFeatureExtractor                                    0.984591
DummyClassifier      HandcraftedFeatureExtractor                             0.092418
KNeighborsClassifier NoneFeatureExtractor                                    0.999999
LogisticRegression   HandcraftedFeatureExtractor                             0.973980
                     NoneFeatureExtractor                                    1.000000
                     ibm-granite/granite-timeseries-patchtsmixer             0.375252


                                                                 ibm-granite/granite-timeseries-patchtsmixer
CustomKernelSVC      NoneFeatureExtractor                                                           0.802694
DummyClassifier      HandcraftedFeatureExtractor                                                    0.984591
KNeighborsClassifier NoneFeatureExtractor                                                           0.427525
LogisticRegression   HandcraftedFeatureExtractor                                                    0.845079
                     NoneFeatureExtractor                                                           0.375252
                     ibm-granite/granite-timeseries-patchtsmixer                                    1.000000