In [1]:
from sys import path

path.append("../")

from edamame_downstream.utils.result_presentation import get_results_path, present_results

## Comparison of feature scaling methods (NO SLIDING WINDOW)

### USILaughs

I noticed that various scaling methods hava an impact on the model performance, especially the handcrafted features. Hence, I try a bunch of different configurations, considering various combinations of mixed, tonic and phasic. The feature scaling is always z-scoring, but that should have a minimum impact on the results.

In [2]:
import pandas as pd
from IPython.display import display, HTML

# Widen the notebook output area
display(HTML("<style>.container { width:98% !important; }</style>"))

# Make DataFrame display larger/more detailed
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 200)   # increase if you want to show more rows
pd.set_option("display.width", 2000)
pd.set_option("display.max_colwidth", None)
pd.set_option("display.colheader_justify", "center")

The results below use the Efficient model trained on the phasic component, using sample-wise min-max normalization, and trained on all datasets.

In [ ]:
# TODO: `only_last` does not work as intended. It should consider only the last multirun for each
# dataset, regardless of the others.
all_results = get_results_path(only_last=True, specific_path="multirun_2025-11-17-10-39-57")

# TODO: the error from the average over seed is not computed correctly.
results_lopo = present_results(
    all_results,
    val_method="lopo",
    remove_xgboost=False,
    remove_chronos_small_from_test=True,
    average_over_seed=True,
    show_tests=False
)

                                                                                                                                                                          Seed accuracy_score balanced_accuracy_score   f1_score   matthews_corrcoef precision_score recall_score roc_auc_score
Aggregator         Dataset   Features                    Label Name    Model              Resampling Side  Validation Channels  Feature Scaling Sample Scaling
MeanChanAggregator usilaughs efficientnet                cognitiveload LogisticRegression None       right LOPO       [0, 1, 2] StandardScaler  empty_scaler              NaN    0.68 ± 0.05         0.66 ± 0.07       0.73 ± 0.04     0.32 ± 0.14      0.86 ± 0.07   0.72 ± 0.09   0.66 ± 0.07
                                                                                                                                                min_max_scaling           NaN    0.76 ± 0.08         0.73 ± 0.09       0.79 ± 0.08     0.47 ± 0.19      0.84 ± 0.09   0.80 ± 0.10   0.73 ± 0.09
                                                                                                                                                min_max_scaling_per_user  NaN    0.73 ± 0.10         0.71 ± 0.11       0.79 ± 0.08     0.42 ± 0.22      0.84 ± 0.08   0.78 ± 0.09   0.71 ± 0.11
                                                                                                                                                z_norm                    NaN    0.60 ± 0.11         0.60 ± 0.11       0.61 ± 0.13     0.20 ± 0.22      0.66 ± 0.14   0.60 ± 0.14   0.60 ± 0.11
                                                                                                                      [0]       StandardScaler  empty_scaler              NaN    0.71 ± 0.04         0.68 ± 0.06       0.76 ± 0.04     0.37 ± 0.12      0.87 ± 0.06   0.77 ± 0.09   0.68 ± 0.06
                                                                                                                                                min_max_scaling           NaN    0.58 ± 0.08         0.51 ± 0.08       0.64 ± 0.10     0.02 ± 0.15      0.62 ± 0.11   0.72 ± 0.13   0.51 ± 0.08
                                                                                                                                                min_max_scaling_per_user  NaN    0.71 ± 0.10         0.68 ± 0.11       0.78 ± 0.08     0.35 ± 0.23      0.81 ± 0.08   0.78 ± 0.09   0.68 ± 0.11
                                                                                                                                                z_norm                    NaN    0.59 ± 0.09         0.54 ± 0.10       0.66 ± 0.09     0.08 ± 0.20      0.70 ± 0.10   0.68 ± 0.11   0.54 ± 0.10
                                                                                                                      [1, 2]    StandardScaler  empty_scaler              NaN    0.68 ± 0.05         0.68 ± 0.07       0.72 ± 0.04     0.35 ± 0.14      0.88 ± 0.07   0.68 ± 0.09   0.68 ± 0.07
                                                                                                                                                min_max_scaling           NaN    0.81 ± 0.07         0.79 ± 0.08       0.85 ± 0.06     0.58 ± 0.16      0.91 ± 0.06   0.85 ± 0.08   0.79 ± 0.08
                                                                                                                                                min_max_scaling_per_user  NaN    0.80 ± 0.09         0.80 ± 0.09       0.81 ± 0.10     0.60 ± 0.18      0.86 ± 0.10   0.80 ± 0.11   0.80 ± 0.09
                                                                                                                                                z_norm                    NaN    0.60 ± 0.12         0.62 ± 0.11       0.57 ± 0.15     0.23 ± 0.23      0.61 ± 0.16   0.57 ± 0.16   0.62 ± 0.11
                                                                                                                      [1]       StandardScaler  empty_scaler              NaN    0.70 ± 0.05         0.68 ± 0.07       0.75 ± 0.04     0.35 ± 0.14      0.86 ± 0.06   0.75 ± 0.09   0.68 ± 0.07
                                                                                                                                                min_max_scaling           NaN    0.64 ± 0.09         0.67 ± 0.09       0.63 ± 0.12     0.33 ± 0.18      0.72 ± 0.14   0.60 ± 0.13   0.67 ± 0.09
                                                                                                                                                min_max_scaling_per_user  NaN    0.76 ± 0.10         0.73 ± 0.12       0.80 ± 0.09     0.47 ± 0.23      0.84 ± 0.09   0.80 ± 0.10   0.73 ± 0.12
                                                                                                                                                z_norm                    NaN    0.66 ± 0.09         0.66 ± 0.09       0.65 ± 0.12     0.32 ± 0.19      0.70 ± 0.13   0.65 ± 0.14   0.66 ± 0.09
                                                                                                                      [2]       StandardScaler  empty_scaler              NaN    0.69 ± 0.08         0.69 ± 0.08       0.67 ± 0.12     0.38 ± 0.16      0.73 ± 0.13   0.68 ± 0.14   0.69 ± 0.08
                                                                                                                                                min_max_scaling           NaN    0.83 ± 0.06         0.82 ± 0.07       0.86 ± 0.05     0.63 ± 0.15      0.92 ± 0.05   0.87 ± 0.08   0.82 ± 0.07
                                                                                                                                                min_max_scaling_per_user  NaN    0.71 ± 0.08         0.68 ± 0.09       0.75 ± 0.09     0.37 ± 0.18      0.78 ± 0.10   0.77 ± 0.11   0.68 ± 0.09
                                                                                                                                                z_norm                    NaN    0.63 ± 0.10         0.62 ± 0.11       0.66 ± 0.11     0.25 ± 0.22      0.71 ± 0.13   0.65 ± 0.13   0.62 ± 0.11
None               usilaughs HandcraftedFeatureExtractor cognitiveload DummyClassifier    None       right LOPO       [0, 1, 2] StandardScaler  empty_scaler              NaN    0.67 ± 0.00         0.50 ± 0.00       0.80 ± 0.00     0.00 ± 0.00      0.67 ± 0.00   1.00 ± 0.00   0.50 ± 0.00
                                                                                                                                                min_max_scaling           NaN    0.67 ± 0.00         0.50 ± 0.00       0.80 ± 0.00     0.00 ± 0.00      0.67 ± 0.00   1.00 ± 0.00   0.50 ± 0.00
                                                                                                                                                min_max_scaling_per_user  NaN    0.67 ± 0.00         0.50 ± 0.00       0.80 ± 0.00     0.00 ± 0.00      0.67 ± 0.00   1.00 ± 0.00   0.50 ± 0.00
                                                                                                                                                z_norm                    NaN    0.67 ± 0.00         0.50 ± 0.00       0.80 ± 0.00     0.00 ± 0.00      0.67 ± 0.00   1.00 ± 0.00   0.50 ± 0.00
                                                                                                                      [0]       StandardScaler  empty_scaler              NaN    0.67 ± 0.00         0.50 ± 0.00       0.80 ± 0.00     0.00 ± 0.00      0.67 ± 0.00   1.00 ± 0.00   0.50 ± 0.00
                                                                                                                                                min_max_scaling           NaN    0.67 ± 0.00         0.50 ± 0.00       0.80 ± 0.00     0.00 ± 0.00      0.67 ± 0.00   1.00 ± 0.00   0.50 ± 0.00
                                                                                                                                                min_max_scaling_per_user  NaN    0.67 ± 0.00         0.50 ± 0.00       0.80 ± 0.00     0.00 ± 0.00      0.67 ± 0.00   1.00 ± 0.00   0.50 ± 0.00
                                                                                                                                                z_norm                    NaN    0.67 ± 0.00         0.50 ± 0.00       0.80 ± 0.00     0.00 ± 0.00      0.67 ± 0.00   1.00 ± 0.00   0.50 ± 0.00
                                                                                                                      [1, 2]    StandardScaler  empty_scaler              NaN    0.67 ± 0.00         0.50 ± 0.00       0.80 ± 0.00     0.00 ± 0.00      0.67 ± 0.00   1.00 ± 0.00   0.50 ± 0.00
                                                                                                                                                min_max_scaling           NaN    0.67 ± 0.00         0.50 ± 0.00       0.80 ± 0.00     0.00 ± 0.00      0.67 ± 0.00   1.00 ± 0.00   0.50 ± 0.00
                                                                                                                                                min_max_scaling_per_user  NaN    0.67 ± 0.00         0.50 ± 0.00       0.80 ± 0.00     0.00 ± 0.00      0.67 ± 0.00   1.00 ± 0.00   0.50 ± 0.00
                                                                                                                                                z_norm                    NaN    0.67 ± 0.00         0.50 ± 0.00       0.80 ± 0.00     0.00 ± 0.00      0.67 ± 0.00   1.00 ± 0.00   0.50 ± 0.00
                                                                                                                      [1]       StandardScaler  empty_scaler              NaN    0.67 ± 0.00         0.50 ± 0.00       0.80 ± 0.00     0.00 ± 0.00      0.67 ± 0.00   1.00 ± 0.00   0.50 ± 0.00
                                                                                                                                                min_max_scaling           NaN    0.67 ± 0.00         0.50 ± 0.00       0.80 ± 0.00     0.00 ± 0.00      0.67 ± 0.00   1.00 ± 0.00   0.50 ± 0.00
                                                                                                                                                min_max_scaling_per_user  NaN    0.67 ± 0.00         0.50 ± 0.00       0.80 ± 0.00     0.00 ± 0.00      0.67 ± 0.00   1.00 ± 0.00   0.50 ± 0.00
                                                                                                                                                z_norm                    NaN    0.67 ± 0.00         0.50 ± 0.00       0.80 ± 0.00     0.00 ± 0.00      0.67 ± 0.00   1.00 ± 0.00   0.50 ± 0.00
                                                                                                                      [2]       StandardScaler  empty_scaler              NaN    0.67 ± 0.00         0.50 ± 0.00       0.80 ± 0.00     0.00 ± 0.00      0.67 ± 0.00   1.00 ± 0.00   0.50 ± 0.00
                                                                                                                                                min_max_scaling           NaN    0.67 ± 0.00         0.50 ± 0.00       0.80 ± 0.00     0.00 ± 0.00      0.67 ± 0.00   1.00 ± 0.00   0.50 ± 0.00
                                                                                                                                                min_max_scaling_per_user  NaN    0.67 ± 0.00         0.50 ± 0.00       0.80 ± 0.00     0.00 ± 0.00      0.67 ± 0.00   1.00 ± 0.00   0.50 ± 0.00
                                                                                                                                                z_norm                    NaN    0.67 ± 0.00         0.50 ± 0.00       0.80 ± 0.00     0.00 ± 0.00      0.67 ± 0.00   1.00 ± 0.00   0.50 ± 0.00
                                                                       LogisticRegression None       right LOPO       [0, 1, 2] StandardScaler  empty_scaler              NaN    0.70 ± 0.09         0.70 ± 0.09       0.70 ± 0.11     0.40 ± 0.19      0.77 ± 0.13   0.70 ± 0.13   0.70 ± 0.09
                                                                                                                                                min_max_scaling           NaN    0.80 ± 0.08         0.78 ± 0.09       0.81 ± 0.10     0.57 ± 0.18      0.84 ± 0.10   0.83 ± 0.11   0.78 ± 0.09
                                                                                                                                                min_max_scaling_per_user  NaN    0.86 ± 0.07         0.85 ± 0.08       0.88 ± 0.06     0.70 ± 0.15      0.94 ± 0.05   0.87 ± 0.08   0.85 ± 0.08
                                                                                                                                                z_norm                    NaN    0.76 ± 0.08         0.73 ± 0.09       0.78 ± 0.10     0.47 ± 0.18      0.81 ± 0.10   0.80 ± 0.11   0.73 ± 0.09
                                                                                                                      [0]       StandardScaler  empty_scaler              NaN    0.71 ± 0.06         0.72 ± 0.07       0.74 ± 0.07     0.43 ± 0.14      0.87 ± 0.08   0.70 ± 0.10   0.72 ± 0.07
                                                                                                                                                min_max_scaling           NaN    0.57 ± 0.07         0.54 ± 0.09       0.63 ± 0.08     0.08 ± 0.17      0.71 ± 0.10   0.62 ± 0.10   0.54 ± 0.09
                                                                                                                                                min_max_scaling_per_user  NaN    0.68 ± 0.09         0.69 ± 0.10       0.69 ± 0.10     0.38 ± 0.19      0.83 ± 0.11   0.65 ± 0.12   0.69 ± 0.10
                                                                                                                                                z_norm                    NaN    0.57 ± 0.09         0.52 ± 0.10       0.63 ± 0.10     0.03 ± 0.20      0.63 ± 0.11   0.67 ± 0.12   0.52 ± 0.10
                                                                                                                      [1, 2]    StandardScaler  empty_scaler              NaN    0.71 ± 0.09         0.72 ± 0.09       0.70 ± 0.12     0.43 ± 0.18      0.77 ± 0.13   0.70 ± 0.13   0.72 ± 0.09
                                                                                                                                                min_max_scaling           NaN    0.81 ± 0.08         0.80 ± 0.08       0.82 ± 0.09     0.60 ± 0.16      0.86 ± 0.10   0.83 ± 0.11   0.80 ± 0.08
                                                                                                                                                min_max_scaling_per_user  NaN    0.89 ± 0.06         0.90 ± 0.06       0.90 ± 0.05     0.80 ± 0.11      0.98 ± 0.03   0.87 ± 0.08   0.90 ± 0.06
                                                                                                                                                z_norm                    NaN    0.76 ± 0.08         0.74 ± 0.09       0.79 ± 0.08     0.48 ± 0.19      0.85 ± 0.09   0.78 ± 0.10   0.74 ± 0.09
                                                                                                                      [1]       StandardScaler  empty_scaler              NaN    0.71 ± 0.07         0.70 ± 0.08       0.75 ± 0.07     0.40 ± 0.16      0.84 ± 0.09   0.73 ± 0.10   0.70 ± 0.08
                                                                                                                                                min_max_scaling           NaN    0.66 ± 0.09         0.68 ± 0.09       0.65 ± 0.11     0.35 ± 0.18      0.76 ± 0.13   0.62 ± 0.12   0.68 ± 0.09
                                                                                                                                                min_max_scaling_per_user  NaN    0.79 ± 0.08         0.80 ± 0.08       0.79 ± 0.10     0.60 ± 0.16      0.87 ± 0.10   0.77 ± 0.11   0.80 ± 0.08
                                                                                                                                                z_norm                    NaN    0.69 ± 0.08         0.71 ± 0.08       0.68 ± 0.11     0.42 ± 0.15      0.78 ± 0.13   0.65 ± 0.13   0.71 ± 0.08
                                                                                                                      [2]       StandardScaler  empty_scaler              NaN    0.66 ± 0.11         0.64 ± 0.12       0.69 ± 0.11     0.28 ± 0.23      0.76 ± 0.12   0.68 ± 0.12   0.64 ± 0.12
                                                                                                                                                min_max_scaling           NaN    0.84 ± 0.07         0.83 ± 0.08       0.86 ± 0.08     0.67 ± 0.15      0.90 ± 0.08   0.87 ± 0.09   0.83 ± 0.08
                                                                                                                                                min_max_scaling_per_user  NaN    0.93 ± 0.05         0.94 ± 0.05       0.94 ± 0.05     0.88 ± 0.09      0.99 ± 0.02   0.92 ± 0.07   0.94 ± 0.05
                                                                                                                                                z_norm                    NaN    0.80 ± 0.08         0.79 ± 0.09       0.82 ± 0.08     0.58 ± 0.18      0.88 ± 0.09   0.82 ± 0.10   0.79 ± 0.09
                             paris-noah/Mantis-8M        cognitiveload LogisticRegression None       right LOPO       [0, 1, 2] StandardScaler  empty_scaler              NaN    0.73 ± 0.09         0.72 ± 0.09       0.76 ± 0.10     0.43 ± 0.19      0.81 ± 0.10   0.77 ± 0.11   0.72 ± 0.09
                                                                                                                                                min_max_scaling           NaN    0.69 ± 0.09         0.66 ± 0.10       0.72 ± 0.11     0.32 ± 0.20      0.75 ± 0.11   0.75 ± 0.12   0.66 ± 0.10
                                                                                                                                                min_max_scaling_per_user  NaN    0.63 ± 0.09         0.61 ± 0.10       0.69 ± 0.09     0.22 ± 0.19      0.76 ± 0.10   0.68 ± 0.11   0.61 ± 0.10
                                                                                                                                                z_norm                    NaN    0.59 ± 0.09         0.57 ± 0.09       0.61 ± 0.11     0.15 ± 0.18      0.66 ± 0.13   0.62 ± 0.13   0.57 ± 0.09
                                                                                                                      [0]       StandardScaler  empty_scaler              NaN    0.71 ± 0.09         0.70 ± 0.10       0.74 ± 0.10     0.40 ± 0.20      0.82 ± 0.10   0.73 ± 0.11   0.70 ± 0.10
                                                                                                                                                min_max_scaling           NaN    0.56 ± 0.10         0.51 ± 0.11       0.62 ± 0.11     0.02 ± 0.21      0.65 ± 0.12   0.65 ± 0.13   0.51 ± 0.11
                                                                                                                                                min_max_scaling_per_user  NaN    0.66 ± 0.09         0.67 ± 0.10       0.67 ± 0.10     0.33 ± 0.20      0.79 ± 0.12   0.63 ± 0.12   0.67 ± 0.10

These results use the Efficient model trained on the phasic component, without any normalization and trained on the BiHeartS dataset only.

In [14]:
# TODO: `only_last` does not work as intended. It should consider only the last multirun for each
# dataset, regardless of the others.
all_results = get_results_path(only_last=True, specific_path="multirun_2025-11-17-10-30-27")

# TODO: the error from the average over seed is not computed correctly.
results_lopo = present_results(
    all_results,
    val_method="lopo",
    remove_xgboost=False,
    remove_chronos_small_from_test=True,
    average_over_seed=True,
    show_tests=False
)

                                                                                                                                                                          Seed accuracy_score balanced_accuracy_score   f1_score   matthews_corrcoef precision_score recall_score roc_auc_score
Aggregator         Dataset   Features                    Label Name    Model              Resampling Side  Validation Channels  Feature Scaling Sample Scaling
MeanChanAggregator usilaughs efficientnet                cognitiveload LogisticRegression None       right LOPO       [0, 1, 2] StandardScaler  empty_scaler              NaN    0.71 ± 0.06         0.69 ± 0.08       0.76 ± 0.05     0.38 ± 0.16      0.87 ± 0.07   0.75 ± 0.09   0.69 ± 0.08
                                                                                                                                                min_max_scaling           NaN    0.68 ± 0.09         0.64 ± 0.11       0.74 ± 0.08     0.28 ± 0.21      0.79 ± 0.09   0.75 ± 0.10   0.64 ± 0.11
                                                                                                                                                min_max_scaling_per_user  NaN    0.70 ± 0.09         0.70 ± 0.09       0.71 ± 0.11     0.40 ± 0.18      0.78 ± 0.12   0.70 ± 0.12   0.70 ± 0.09
                                                                                                                                                z_norm                    NaN    0.64 ± 0.08         0.62 ± 0.08       0.67 ± 0.10     0.25 ± 0.17      0.73 ± 0.11   0.68 ± 0.12   0.62 ± 0.08
                                                                                                                      [0]       StandardScaler  empty_scaler              NaN    0.70 ± 0.07         0.68 ± 0.08       0.75 ± 0.06     0.37 ± 0.16      0.86 ± 0.07   0.73 ± 0.09   0.68 ± 0.08
                                                                                                                                                min_max_scaling           NaN    0.54 ± 0.08         0.53 ± 0.09       0.57 ± 0.10     0.07 ± 0.18      0.66 ± 0.13   0.57 ± 0.12   0.53 ± 0.09
                                                                                                                                                min_max_scaling_per_user  NaN    0.64 ± 0.10         0.63 ± 0.11       0.68 ± 0.10     0.27 ± 0.23      0.76 ± 0.12   0.67 ± 0.12   0.63 ± 0.11
                                                                                                                                                z_norm                    NaN    0.58 ± 0.08         0.57 ± 0.09       0.60 ± 0.10     0.15 ± 0.17      0.68 ± 0.12   0.58 ± 0.12   0.57 ± 0.09
                                                                                                                      [1, 2]    StandardScaler  empty_scaler              NaN    0.70 ± 0.06         0.68 ± 0.08       0.76 ± 0.05     0.35 ± 0.15      0.86 ± 0.07   0.75 ± 0.09   0.68 ± 0.08
                                                                                                                                                min_max_scaling           NaN    0.70 ± 0.09         0.67 ± 0.10       0.74 ± 0.09     0.33 ± 0.19      0.77 ± 0.10   0.77 ± 0.11   0.67 ± 0.10
                                                                                                                                                min_max_scaling_per_user  NaN    0.70 ± 0.09         0.71 ± 0.09       0.69 ± 0.12     0.42 ± 0.18      0.76 ± 0.13   0.68 ± 0.13   0.71 ± 0.09
                                                                                                                                                z_norm                    NaN    0.64 ± 0.10         0.63 ± 0.11       0.66 ± 0.12     0.27 ± 0.22      0.71 ± 0.13   0.67 ± 0.14   0.63 ± 0.11
                                                                                                                      [1]       StandardScaler  empty_scaler              NaN    0.70 ± 0.06         0.68 ± 0.08       0.76 ± 0.05     0.35 ± 0.15      0.86 ± 0.07   0.75 ± 0.09   0.68 ± 0.08
                                                                                                                                                min_max_scaling           NaN    0.64 ± 0.08         0.63 ± 0.09       0.68 ± 0.09     0.27 ± 0.19      0.77 ± 0.11   0.67 ± 0.11   0.63 ± 0.09
                                                                                                                                                min_max_scaling_per_user  NaN    0.64 ± 0.09         0.65 ± 0.10       0.65 ± 0.11     0.30 ± 0.20      0.72 ± 0.13   0.63 ± 0.12   0.65 ± 0.10
                                                                                                                                                z_norm                    NaN    0.70 ± 0.11         0.69 ± 0.11       0.70 ± 0.13     0.38 ± 0.22      0.74 ± 0.13   0.72 ± 0.14   0.69 ± 0.11
                                                                                                                      [2]       StandardScaler  empty_scaler              NaN    0.51 ± 0.11         0.48 ± 0.11       0.55 ± 0.13    -0.05 ± 0.22      0.56 ± 0.13   0.58 ± 0.14   0.48 ± 0.11
                                                                                                                                                min_max_scaling           NaN    0.78 ± 0.08         0.76 ± 0.09       0.81 ± 0.08     0.52 ± 0.18      0.86 ± 0.09   0.82 ± 0.10   0.76 ± 0.09
                                                                                                                                                min_max_scaling_per_user  NaN    0.83 ± 0.07         0.84 ± 0.07       0.84 ± 0.08     0.68 ± 0.14      0.92 ± 0.08   0.82 ± 0.10   0.84 ± 0.07
                                                                                                                                                z_norm                    NaN    0.78 ± 0.08         0.77 ± 0.09       0.82 ± 0.07     0.53 ± 0.18      0.89 ± 0.07   0.80 ± 0.09   0.77 ± 0.09
None               usilaughs HandcraftedFeatureExtractor cognitiveload DummyClassifier    None       right LOPO       [0, 1, 2] StandardScaler  empty_scaler              NaN    0.67 ± 0.00         0.50 ± 0.00       0.80 ± 0.00     0.00 ± 0.00      0.67 ± 0.00   1.00 ± 0.00   0.50 ± 0.00
                                                                                                                                                min_max_scaling           NaN    0.67 ± 0.00         0.50 ± 0.00       0.80 ± 0.00     0.00 ± 0.00      0.67 ± 0.00   1.00 ± 0.00   0.50 ± 0.00
                                                                                                                                                min_max_scaling_per_user  NaN    0.67 ± 0.00         0.50 ± 0.00       0.80 ± 0.00     0.00 ± 0.00      0.67 ± 0.00   1.00 ± 0.00   0.50 ± 0.00
                                                                                                                                                z_norm                    NaN    0.67 ± 0.00         0.50 ± 0.00       0.80 ± 0.00     0.00 ± 0.00      0.67 ± 0.00   1.00 ± 0.00   0.50 ± 0.00
                                                                                                                      [0]       StandardScaler  empty_scaler              NaN    0.67 ± 0.00         0.50 ± 0.00       0.80 ± 0.00     0.00 ± 0.00      0.67 ± 0.00   1.00 ± 0.00   0.50 ± 0.00
                                                                                                                                                min_max_scaling           NaN    0.67 ± 0.00         0.50 ± 0.00       0.80 ± 0.00     0.00 ± 0.00      0.67 ± 0.00   1.00 ± 0.00   0.50 ± 0.00
                                                                                                                                                min_max_scaling_per_user  NaN    0.67 ± 0.00         0.50 ± 0.00       0.80 ± 0.00     0.00 ± 0.00      0.67 ± 0.00   1.00 ± 0.00   0.50 ± 0.00
                                                                                                                                                z_norm                    NaN    0.67 ± 0.00         0.50 ± 0.00       0.80 ± 0.00     0.00 ± 0.00      0.67 ± 0.00   1.00 ± 0.00   0.50 ± 0.00
                                                                                                                      [1, 2]    StandardScaler  empty_scaler              NaN    0.67 ± 0.00         0.50 ± 0.00       0.80 ± 0.00     0.00 ± 0.00      0.67 ± 0.00   1.00 ± 0.00   0.50 ± 0.00
                                                                                                                                                min_max_scaling           NaN    0.67 ± 0.00         0.50 ± 0.00       0.80 ± 0.00     0.00 ± 0.00      0.67 ± 0.00   1.00 ± 0.00   0.50 ± 0.00
                                                                                                                                                min_max_scaling_per_user  NaN    0.67 ± 0.00         0.50 ± 0.00       0.80 ± 0.00     0.00 ± 0.00      0.67 ± 0.00   1.00 ± 0.00   0.50 ± 0.00
                                                                                                                                                z_norm                    NaN    0.67 ± 0.00         0.50 ± 0.00       0.80 ± 0.00     0.00 ± 0.00      0.67 ± 0.00   1.00 ± 0.00   0.50 ± 0.00
                                                                                                                      [1]       StandardScaler  empty_scaler              NaN    0.67 ± 0.00         0.50 ± 0.00       0.80 ± 0.00     0.00 ± 0.00      0.67 ± 0.00   1.00 ± 0.00   0.50 ± 0.00
                                                                                                                                                min_max_scaling           NaN    0.67 ± 0.00         0.50 ± 0.00       0.80 ± 0.00     0.00 ± 0.00      0.67 ± 0.00   1.00 ± 0.00   0.50 ± 0.00
                                                                                                                                                min_max_scaling_per_user  NaN    0.67 ± 0.00         0.50 ± 0.00       0.80 ± 0.00     0.00 ± 0.00      0.67 ± 0.00   1.00 ± 0.00   0.50 ± 0.00
                                                                                                                                                z_norm                    NaN    0.67 ± 0.00         0.50 ± 0.00       0.80 ± 0.00     0.00 ± 0.00      0.67 ± 0.00   1.00 ± 0.00   0.50 ± 0.00
                                                                                                                      [2]       StandardScaler  empty_scaler              NaN    0.67 ± 0.00         0.50 ± 0.00       0.80 ± 0.00     0.00 ± 0.00      0.67 ± 0.00   1.00 ± 0.00   0.50 ± 0.00
                                                                                                                                                min_max_scaling           NaN    0.67 ± 0.00         0.50 ± 0.00       0.80 ± 0.00     0.00 ± 0.00      0.67 ± 0.00   1.00 ± 0.00   0.50 ± 0.00
                                                                                                                                                min_max_scaling_per_user  NaN    0.67 ± 0.00         0.50 ± 0.00       0.80 ± 0.00     0.00 ± 0.00      0.67 ± 0.00   1.00 ± 0.00   0.50 ± 0.00
                                                                                                                                                z_norm                    NaN    0.67 ± 0.00         0.50 ± 0.00       0.80 ± 0.00     0.00 ± 0.00      0.67 ± 0.00   1.00 ± 0.00   0.50 ± 0.00
                                                                       LogisticRegression None       right LOPO       [0, 1, 2] StandardScaler  empty_scaler              NaN    0.70 ± 0.09         0.70 ± 0.09       0.70 ± 0.11     0.40 ± 0.19      0.77 ± 0.13   0.70 ± 0.13   0.70 ± 0.09
                                                                                                                                                min_max_scaling           NaN    0.80 ± 0.08         0.78 ± 0.09       0.81 ± 0.10     0.57 ± 0.18      0.84 ± 0.10   0.83 ± 0.11   0.78 ± 0.09
                                                                                                                                                min_max_scaling_per_user  NaN    0.86 ± 0.07         0.85 ± 0.08       0.88 ± 0.06     0.70 ± 0.15      0.94 ± 0.05   0.87 ± 0.08   0.85 ± 0.08
                                                                                                                                                z_norm                    NaN    0.76 ± 0.08         0.73 ± 0.09       0.78 ± 0.10     0.47 ± 0.18      0.81 ± 0.10   0.80 ± 0.11   0.73 ± 0.09
                                                                                                                      [0]       StandardScaler  empty_scaler              NaN    0.71 ± 0.06         0.72 ± 0.07       0.74 ± 0.07     0.43 ± 0.14      0.87 ± 0.08   0.70 ± 0.10   0.72 ± 0.07
                                                                                                                                                min_max_scaling           NaN    0.57 ± 0.07         0.54 ± 0.09       0.63 ± 0.08     0.08 ± 0.17      0.71 ± 0.10   0.62 ± 0.10   0.54 ± 0.09
                                                                                                                                                min_max_scaling_per_user  NaN    0.68 ± 0.09         0.69 ± 0.10       0.69 ± 0.10     0.38 ± 0.19      0.83 ± 0.11   0.65 ± 0.12   0.69 ± 0.10
                                                                                                                                                z_norm                    NaN    0.57 ± 0.09         0.52 ± 0.10       0.63 ± 0.10     0.03 ± 0.20      0.63 ± 0.11   0.67 ± 0.12   0.52 ± 0.10
                                                                                                                      [1, 2]    StandardScaler  empty_scaler              NaN    0.71 ± 0.09         0.72 ± 0.09       0.70 ± 0.12     0.43 ± 0.18      0.77 ± 0.13   0.70 ± 0.13   0.72 ± 0.09
                                                                                                                                                min_max_scaling           NaN    0.81 ± 0.08         0.80 ± 0.08       0.82 ± 0.09     0.60 ± 0.16      0.86 ± 0.10   0.83 ± 0.11   0.80 ± 0.08
                                                                                                                                                min_max_scaling_per_user  NaN    0.89 ± 0.06         0.90 ± 0.06       0.90 ± 0.05     0.80 ± 0.11      0.98 ± 0.03   0.87 ± 0.08   0.90 ± 0.06
                                                                                                                                                z_norm                    NaN    0.76 ± 0.08         0.74 ± 0.09       0.79 ± 0.08     0.48 ± 0.19      0.85 ± 0.09   0.78 ± 0.10   0.74 ± 0.09
                                                                                                                      [1]       StandardScaler  empty_scaler              NaN    0.71 ± 0.07         0.70 ± 0.08       0.75 ± 0.07     0.40 ± 0.16      0.84 ± 0.09   0.73 ± 0.10   0.70 ± 0.08
                                                                                                                                                min_max_scaling           NaN    0.66 ± 0.09         0.68 ± 0.09       0.65 ± 0.11     0.35 ± 0.18      0.76 ± 0.13   0.62 ± 0.12   0.68 ± 0.09
                                                                                                                                                min_max_scaling_per_user  NaN    0.79 ± 0.08         0.80 ± 0.08       0.79 ± 0.10     0.60 ± 0.16      0.87 ± 0.10   0.77 ± 0.11   0.80 ± 0.08
                                                                                                                                                z_norm                    NaN    0.69 ± 0.08         0.71 ± 0.08       0.68 ± 0.11     0.42 ± 0.15      0.78 ± 0.13   0.65 ± 0.13   0.71 ± 0.08
                                                                                                                      [2]       StandardScaler  empty_scaler              NaN    0.66 ± 0.11         0.64 ± 0.12       0.69 ± 0.11     0.28 ± 0.23      0.76 ± 0.12   0.68 ± 0.12   0.64 ± 0.12
                                                                                                                                                min_max_scaling           NaN    0.84 ± 0.07         0.83 ± 0.08       0.86 ± 0.08     0.67 ± 0.15      0.90 ± 0.08   0.87 ± 0.09   0.83 ± 0.08
                                                                                                                                                min_max_scaling_per_user  NaN    0.93 ± 0.05         0.94 ± 0.05       0.94 ± 0.05     0.88 ± 0.09      0.99 ± 0.02   0.92 ± 0.07   0.94 ± 0.05
                                                                                                                                                z_norm                    NaN    0.80 ± 0.08         0.79 ± 0.09       0.82 ± 0.08     0.58 ± 0.18      0.88 ± 0.09   0.82 ± 0.10   0.79 ± 0.09
                             paris-noah/Mantis-8M        cognitiveload LogisticRegression None       right LOPO       [0, 1, 2] StandardScaler  empty_scaler              NaN    0.73 ± 0.09         0.72 ± 0.09       0.76 ± 0.10     0.43 ± 0.19      0.81 ± 0.10   0.77 ± 0.11   0.72 ± 0.09
                                                                                                                                                min_max_scaling           NaN    0.69 ± 0.09         0.66 ± 0.10       0.72 ± 0.11     0.32 ± 0.20      0.75 ± 0.11   0.75 ± 0.12   0.66 ± 0.10
                                                                                                                                                min_max_scaling_per_user  NaN    0.63 ± 0.09         0.61 ± 0.10       0.69 ± 0.09     0.22 ± 0.19      0.76 ± 0.10   0.68 ± 0.11   0.61 ± 0.10
                                                                                                                                                z_norm                    NaN    0.59 ± 0.09         0.57 ± 0.09       0.61 ± 0.11     0.15 ± 0.18      0.66 ± 0.13   0.62 ± 0.13   0.57 ± 0.09
                                                                                                                      [0]       StandardScaler  empty_scaler              NaN    0.71 ± 0.09         0.70 ± 0.10       0.74 ± 0.10     0.40 ± 0.20      0.82 ± 0.10   0.73 ± 0.11   0.70 ± 0.10
                                                                                                                                                min_max_scaling           NaN    0.56 ± 0.10         0.51 ± 0.11       0.62 ± 0.11     0.02 ± 0.21      0.65 ± 0.12   0.65 ± 0.13   0.51 ± 0.11
                                                                                                                                                min_max_scaling_per_user  NaN    0.66 ± 0.09         0.67 ± 0.10       0.67 ± 0.10     0.33 ± 0.20      0.79 ± 0.12   0.63 ± 0.12   0.67 ± 0.10

Finally, we tried with the LNPO method, using multiple seeds. This should allow to have way smaller errors, so that we can get some statistics out of it.

In [9]:
# TODO: `only_last` does not work as intended. It should consider only the last multirun for each
# dataset, regardless of the others.
all_results = get_results_path(only_last=True, specific_path="multirun_2025-11-18-10-16-03")

# TODO: the error from the average over seed is not computed correctly.
results_lopo = present_results(
    all_results,
    val_method="lnpo",
    remove_xgboost=False,
    remove_chronos_small_from_test=True,
    average_over_seed=True,
    show_tests=False
)

                                                                                                                                                                         Seed accuracy_score balanced_accuracy_score   f1_score   matthews_corrcoef precision_score recall_score roc_auc_score
Aggregator         Dataset   Features                    Label Name    Model              Resampling Side  Validation Channels Feature Scaling Sample Scaling
MeanChanAggregator usilaughs efficientnet                cognitiveload LogisticRegression None       right LNPO       [1]      StandardScaler  empty_scaler              NaN    0.69 ± 0.02         0.66 ± 0.03       0.76 ± 0.01     0.32 ± 0.06      0.79 ± 0.03   0.75 ± 0.03   0.66 ± 0.03
                                                                                                                                               min_max_scaling           NaN    0.66 ± 0.03         0.67 ± 0.02       0.70 ± 0.04     0.33 ± 0.04      0.82 ± 0.02   0.63 ± 0.06   0.67 ± 0.02
                                                                                                                                               min_max_scaling_per_user  NaN    0.73 ± 0.04         0.70 ± 0.05       0.79 ± 0.03     0.40 ± 0.11      0.81 ± 0.04   0.79 ± 0.04   0.70 ± 0.05
                                                                                                                                               z_norm                    NaN    0.65 ± 0.04         0.65 ± 0.05       0.70 ± 0.05     0.29 ± 0.09      0.80 ± 0.05   0.64 ± 0.07   0.65 ± 0.05
                                                                                                                      [2]      StandardScaler  empty_scaler              NaN    0.67 ± 0.03         0.68 ± 0.03       0.72 ± 0.03     0.36 ± 0.06      0.84 ± 0.04   0.66 ± 0.06   0.68 ± 0.03
                                                                                                                                               min_max_scaling           NaN    0.82 ± 0.03         0.80 ± 0.04       0.86 ± 0.03     0.62 ± 0.07      0.88 ± 0.03   0.87 ± 0.04   0.80 ± 0.04
                                                                                                                                               min_max_scaling_per_user  NaN    0.69 ± 0.03         0.67 ± 0.04       0.75 ± 0.03     0.34 ± 0.07      0.80 ± 0.03   0.73 ± 0.05   0.67 ± 0.04
                                                                                                                                               z_norm                    NaN    0.64 ± 0.04         0.65 ± 0.04       0.69 ± 0.04     0.28 ± 0.08      0.80 ± 0.04   0.63 ± 0.05   0.65 ± 0.04
None               usilaughs HandcraftedFeatureExtractor cognitiveload LogisticRegression None       right LNPO       [1]      StandardScaler  empty_scaler              NaN    0.72 ± 0.03         0.70 ± 0.03       0.78 ± 0.02     0.40 ± 0.06      0.82 ± 0.03   0.75 ± 0.04   0.70 ± 0.03
                                                                                                                                               min_max_scaling           NaN    0.65 ± 0.04         0.65 ± 0.04       0.70 ± 0.05     0.29 ± 0.08      0.80 ± 0.04   0.65 ± 0.06   0.65 ± 0.04
                                                                                                                                               min_max_scaling_per_user  NaN    0.73 ± 0.04         0.73 ± 0.04       0.79 ± 0.04     0.46 ± 0.08      0.84 ± 0.03   0.75 ± 0.05   0.73 ± 0.04
                                                                                                                                               z_norm                    NaN    0.66 ± 0.03         0.66 ± 0.04       0.71 ± 0.04     0.32 ± 0.07      0.82 ± 0.04   0.66 ± 0.06   0.66 ± 0.04
                                                                                                                      [2]      StandardScaler  empty_scaler              NaN    0.68 ± 0.04         0.69 ± 0.04       0.73 ± 0.04     0.36 ± 0.08      0.82 ± 0.03   0.68 ± 0.06   0.69 ± 0.04
                                                                                                                                               min_max_scaling           NaN    0.86 ± 0.03         0.85 ± 0.03       0.89 ± 0.02     0.70 ± 0.05      0.92 ± 0.03   0.87 ± 0.04   0.85 ± 0.03
                                                                                                                                               min_max_scaling_per_user  NaN    0.92 ± 0.02         0.93 ± 0.02       0.94 ± 0.02     0.85 ± 0.05      0.97 ± 0.02   0.92 ± 0.03   0.93 ± 0.02
                                                                                                                                               z_norm                    NaN    0.81 ± 0.03         0.81 ± 0.03       0.85 ± 0.03     0.61 ± 0.06      0.89 ± 0.03   0.82 ± 0.04   0.81 ± 0.03
                             paris-noah/Mantis-8M        cognitiveload LogisticRegression None       right LNPO       [1]      StandardScaler  empty_scaler              NaN    0.73 ± 0.04         0.71 ± 0.04       0.79 ± 0.03     0.41 ± 0.08      0.82 ± 0.04   0.77 ± 0.04   0.71 ± 0.04
                                                                                                                                               min_max_scaling           NaN    0.60 ± 0.04         0.59 ± 0.04       0.67 ± 0.05     0.18 ± 0.08      0.74 ± 0.04   0.63 ± 0.07   0.59 ± 0.04
                                                                                                                                               min_max_scaling_per_user  NaN    0.74 ± 0.04         0.75 ± 0.04       0.78 ± 0.04     0.48 ± 0.08      0.87 ± 0.03   0.71 ± 0.06   0.75 ± 0.04
                                                                                                                                               z_norm                    NaN    0.59 ± 0.05         0.57 ± 0.04       0.66 ± 0.05     0.15 ± 0.08      0.71 ± 0.04   0.63 ± 0.07   0.57 ± 0.04
                                                                                                                      [2]      StandardScaler  empty_scaler              NaN    0.57 ± 0.04         0.55 ± 0.04       0.64 ± 0.04     0.11 ± 0.08      0.71 ± 0.03   0.60 ± 0.06   0.55 ± 0.04
                                                                                                                                               min_max_scaling           NaN    0.76 ± 0.02         0.73 ± 0.03       0.82 ± 0.02     0.48 ± 0.06      0.83 ± 0.03   0.81 ± 0.04   0.74 ± 0.03
                                                                                                                                               min_max_scaling_per_user  NaN    0.59 ± 0.03         0.58 ± 0.03       0.65 ± 0.04     0.17 ± 0.07      0.74 ± 0.04   0.61 ± 0.06   0.58 ± 0.03
                                                                                                                                               z_norm                    NaN    0.60 ± 0.04         0.59 ± 0.04       0.67 ± 0.04     0.18 ± 0.08      0.74 ± 0.03   0.62 ± 0.06   0.59 ± 0.04

### BiHeartS

This time, I also present the results of the model pre-trained on BiHeartS. Here, we are staying in-distribution.

In [2]:
# TODO: `only_last` does not work as intended. It should consider only the last multirun for each
# dataset, regardless of the others.
all_results = get_results_path(only_last=True, specific_path="multirun_2025-11-17-13-18-43")

# TODO: the error from the average over seed is not computed correctly.
results_lopo = present_results(
    all_results,
    val_method="lopo",
    remove_xgboost=False,
    remove_chronos_small_from_test=True,
    average_over_seed=True,
    show_tests=False
)

                                                                                                                                                                    Seed  \
Aggregator         Dataset  Features                    Label Name Model              Resampling Side Validation Channels Feature Scaling Sample Scaling
MeanChanAggregator BiHeartS efficientnet                sleep_wake LogisticRegression None       left LOPO       [0]      StandardScaler  empty_scaler               NaN
                                                                                                                                          min_max_scaling            NaN
                                                                                                                                          min_max_scaling_per_user   NaN
                                                                                                                                          z_norm                     NaN
                                                                                                                 [1, 2]   StandardScaler  empty_scaler               NaN
                                                                                                                                          min_max_scaling            NaN
                                                                                                                                          min_max_scaling_per_user   NaN
                                                                                                                                          z_norm                     NaN
                                                                                                                 [1]      StandardScaler  empty_scaler               NaN
                                                                                                                                          min_max_scaling            NaN
                                                                                                                                          min_max_scaling_per_user   NaN
                                                                                                                                          z_norm                     NaN
                                                                                                                 [2]      StandardScaler  empty_scaler               NaN
                                                                                                                                          min_max_scaling            NaN
                                                                                                                                          min_max_scaling_per_user   NaN
                                                                                                                                          z_norm                     NaN
None               BiHeartS HandcraftedFeatureExtractor sleep_wake LogisticRegression None       left LOPO       [0]      StandardScaler  empty_scaler               NaN
                                                                                                                                          min_max_scaling            NaN
                                                                                                                                          min_max_scaling_per_user   NaN
                                                                                                                                          z_norm                     NaN
                                                                                                                 [1, 2]   StandardScaler  empty_scaler               NaN
                                                                                                                                          min_max_scaling            NaN
                                                                                                                                          min_max_scaling_per_user   NaN
                                                                                                                                          z_norm                     NaN
                                                                                                                 [1]      StandardScaler  empty_scaler               NaN
                                                                                                                                          min_max_scaling            NaN
                                                                                                                                          min_max_scaling_per_user   NaN
                                                                                                                                          z_norm                     NaN
                                                                                                                 [2]      StandardScaler  empty_scaler               NaN
                                                                                                                                          min_max_scaling            NaN
                                                                                                                                          min_max_scaling_per_user   NaN
                                                                                                                                          z_norm                     NaN
                            paris-noah/Mantis-8M        sleep_wake LogisticRegression None       left LOPO       [0]      StandardScaler  empty_scaler               NaN
                                                                                                                                          min_max_scaling            NaN
                                                                                                                                          min_max_scaling_per_user   NaN
                                                                                                                                          z_norm                     NaN
                                                                                                                 [1, 2]   StandardScaler  empty_scaler               NaN
                                                                                                                                          min_max_scaling            NaN
                                                                                                                                          min_max_scaling_per_user   NaN
                                                                                                                                          z_norm                     NaN
                                                                                                                 [1]      StandardScaler  empty_scaler               NaN
                                                                                                                                          min_max_scaling            NaN
                                                                                                                                          min_max_scaling_per_user   NaN
                                                                                                                                          z_norm                     NaN
                                                                                                                 [2]      StandardScaler  empty_scaler               NaN
                                                                                                                                          min_max_scaling            NaN
                                                                                                                                          min_max_scaling_per_user   NaN
                                                                                                                                          z_norm                     NaN

                                                                                                                                                                   accuracy_score  \
Aggregator         Dataset  Features                    Label Name Model              Resampling Side Validation Channels Feature Scaling Sample Scaling
MeanChanAggregator BiHeartS efficientnet                sleep_wake LogisticRegression None       left LOPO       [0]      StandardScaler  empty_scaler                0.76 ± 0.07
                                                                                                                                          min_max_scaling             0.66 ± 0.04
                                                                                                                                          min_max_scaling_per_user    0.58 ± 0.08
                                                                                                                                          z_norm                      0.60 ± 0.04
                                                                                                                 [1, 2]   StandardScaler  empty_scaler                0.74 ± 0.04
                                                                                                                                          min_max_scaling             0.66 ± 0.05
                                                                                                                                          min_max_scaling_per_user    0.66 ± 0.16
                                                                                                                                          z_norm                      0.66 ± 0.04
                                                                                                                 [1]      StandardScaler  empty_scaler                0.81 ± 0.04
                                                                                                                                          min_max_scaling             0.66 ± 0.05
                                                                                                                                          min_max_scaling_per_user    0.65 ± 0.16
                                                                                                                                          z_norm                      0.68 ± 0.04
                                                                                                                 [2]      StandardScaler  empty_scaler                0.69 ± 0.05
                                                                                                                                          min_max_scaling             0.65 ± 0.04
                                                                                                                                          min_max_scaling_per_user    0.68 ± 0.11
                                                                                                                                          z_norm                      0.64 ± 0.03
None               BiHeartS HandcraftedFeatureExtractor sleep_wake LogisticRegression None       left LOPO       [0]      StandardScaler  empty_scaler                0.68 ± 0.07
                                                                                                                                          min_max_scaling             0.69 ± 0.03
                                                                                                                                          min_max_scaling_per_user    0.59 ± 0.07
                                                                                                                                          z_norm                      0.68 ± 0.03
                                                                                                                 [1, 2]   StandardScaler  empty_scaler                0.76 ± 0.05
                                                                                                                                          min_max_scaling             0.75 ± 0.04
                                                                                                                                          min_max_scaling_per_user    0.77 ± 0.09
                                                                                                                                          z_norm                      0.75 ± 0.04
                                                                                                                 [1]      StandardScaler  empty_scaler                0.73 ± 0.05
                                                                                                                                          min_max_scaling             0.75 ± 0.04
                                                                                                                                          min_max_scaling_per_user    0.70 ± 0.12
                                                                                                                                          z_norm                      0.75 ± 0.04
                                                                                                                 [2]      StandardScaler  empty_scaler                0.75 ± 0.05
                                                                                                                                          min_max_scaling             0.65 ± 0.04
                                                                                                                                          min_max_scaling_per_user    0.69 ± 0.05
                                                                                                                                          z_norm                      0.65 ± 0.04
                            paris-noah/Mantis-8M        sleep_wake LogisticRegression None       left LOPO       [0]      StandardScaler  empty_scaler                0.77 ± 0.07
                                                                                                                                          min_max_scaling             0.74 ± 0.04
                                                                                                                                          min_max_scaling_per_user    0.74 ± 0.07
                                                                                                                                          z_norm                      0.73 ± 0.04
                                                                                                                 [1, 2]   StandardScaler  empty_scaler                0.83 ± 0.04
                                                                                                                                          min_max_scaling             0.82 ± 0.05
                                                                                                                                          min_max_scaling_per_user    0.74 ± 0.07
                                                                                                                                          z_norm                      0.81 ± 0.05
                                                                                                                 [1]      StandardScaler  empty_scaler                0.82 ± 0.04
                                                                                                                                          min_max_scaling             0.82 ± 0.04
                                                                                                                                          min_max_scaling_per_user    0.76 ± 0.08
                                                                                                                                          z_norm                      0.81 ± 0.05
                                                                                                                 [2]      StandardScaler  empty_scaler                0.75 ± 0.05
                                                                                                                                          min_max_scaling             0.66 ± 0.04
                                                                                                                                          min_max_scaling_per_user    0.70 ± 0.09
                                                                                                                                          z_norm                      0.66 ± 0.04

                                                                                                                                                                   balanced_accuracy_score  \
Aggregator         Dataset  Features                    Label Name Model              Resampling Side Validation Channels Feature Scaling Sample Scaling
MeanChanAggregator BiHeartS efficientnet                sleep_wake LogisticRegression None       left LOPO       [0]      StandardScaler  empty_scaler                         0.66 ± 0.07
                                                                                                                                          min_max_scaling                      0.63 ± 0.05
                                                                                                                                          min_max_scaling_per_user             0.56 ± 0.05
                                                                                                                                          z_norm                               0.59 ± 0.04
                                                                                                                 [1, 2]   StandardScaler  empty_scaler                         0.68 ± 0.07
                                                                                                                                          min_max_scaling                      0.65 ± 0.05
                                                                                                                                          min_max_scaling_per_user             0.53 ± 0.04
                                                                                                                                          z_norm                               0.64 ± 0.05
                                                                                                                 [1]      StandardScaler  empty_scaler                         0.75 ± 0.07
                                                                                                                                          min_max_scaling                      0.65 ± 0.05
                                                                                                                                          min_max_scaling_per_user             0.54 ± 0.05
                                                                                                                                          z_norm                               0.65 ± 0.05

# Model comparison - SLIDING WINDOW

In these experiments, the foundation model has been trained using sliding windows of 0.25s (1 sample), as done by similar researchers in the literature.

### BiHeartS

We present the results for the model trained on the BiHeartS only here, on the phasic component. From the training, the model was overfitting very fast, even a small model, but the representation on the validation set (using windows close together) was still good.

In [2]:
# TODO: `only_last` does not work as intended. It should consider only the last multirun for each
# dataset, regardless of the others.
all_results = get_results_path(only_last=True, specific_path="multirun_2025-11-24-15-46-31")

# TODO: the error from the average over seed is not computed correctly.
results_lopo = present_results(
    all_results,
    val_method="lopo",
    remove_xgboost=False,
    remove_chronos_small_from_test=True,
    average_over_seed=True,
    show_tests=False
)

                                                                                                                                           Seed  \
Aggregator         Dataset  Features     Label Name Model              Resampling Side Validation Channels Feature Scaling Sample Scaling
MeanChanAggregator BiHeartS efficientnet sleep_wake LogisticRegression None       left LOPO       [1]      StandardScaler  empty_scaler     NaN
                                                                                                  [2]      StandardScaler  empty_scaler     NaN

                                                                                                                                          accuracy_score  \
Aggregator         Dataset  Features     Label Name Model              Resampling Side Validation Channels Feature Scaling Sample Scaling
MeanChanAggregator BiHeartS efficientnet sleep_wake LogisticRegression None       left LOPO       [1]      StandardScaler  empty_scaler      0.77 ± 0.05
                                                                                                  [2]      StandardScaler  empty_scaler      0.76 ± 0.05

                                                                                                                                          balanced_accuracy_score  \
Aggregator         Dataset  Features     Label Name Model              Resampling Side Validation Channels Feature Scaling Sample Scaling
MeanChanAggregator BiHeartS efficientnet sleep_wake LogisticRegression None       left LOPO       [1]      StandardScaler  empty_scaler               0.71 ± 0.07
                                                                                                  [2]      StandardScaler  empty_scaler               0.68 ± 0.06

                                                                                                                                              f1_score  \
Aggregator         Dataset  Features     Label Name Model              Resampling Side Validation Channels Feature Scaling Sample Scaling
MeanChanAggregator BiHeartS efficientnet sleep_wake LogisticRegression None       left LOPO       [1]      StandardScaler  empty_scaler    0.53 ± 0.15
                                                                                                  [2]      StandardScaler  empty_scaler    0.50 ± 0.13

                                                                                                                                          matthews_corrcoef  \
Aggregator         Dataset  Features     Label Name Model              Resampling Side Validation Channels Feature Scaling Sample Scaling
MeanChanAggregator BiHeartS efficientnet sleep_wake LogisticRegression None       left LOPO       [1]      StandardScaler  empty_scaler         0.39 ± 0.14
                                                                                                  [2]      StandardScaler  empty_scaler         0.34 ± 0.12

                                                                                                                                          precision_score  \
Aggregator         Dataset  Features     Label Name Model              Resampling Side Validation Channels Feature Scaling Sample Scaling
MeanChanAggregator BiHeartS efficientnet sleep_wake LogisticRegression None       left LOPO       [1]      StandardScaler  empty_scaler       0.55 ± 0.17
                                                                                                  [2]      StandardScaler  empty_scaler       0.52 ± 0.15

                                                                                                                                          recall_score  \
Aggregator         Dataset  Features     Label Name Model              Resampling Side Validation Channels Feature Scaling Sample Scaling
MeanChanAggregator BiHeartS efficientnet sleep_wake LogisticRegression None       left LOPO       [1]      StandardScaler  empty_scaler    0.59 ± 0.13
                                                                                                  [2]      StandardScaler  empty_scaler    0.54 ± 0.13

                                                                                                                                          roc_auc_score
Aggregator         Dataset  Features     Label Name Model              Resampling Side Validation Channels Feature Scaling Sample Scaling
MeanChanAggregator BiHeartS efficientnet sleep_wake LogisticRegression None       left LOPO       [1]      StandardScaler  empty_scaler     0.71 ± 0.07
                                                                                                  [2]      StandardScaler  empty_scaler     0.68 ± 0.06

### USILaughs

In this case, the model is trained only on BiHeartS, but tested on the USILaughs model. The model is trained with a sliding window.

In [5]:
# TODO: `only_last` does not work as intended. It should consider only the last multirun for each
# dataset, regardless of the others.
all_results = get_results_path(only_last=True, specific_path="multirun_2025-11-24-15-55-27")

# TODO: the error from the average over seed is not computed correctly.
results_lopo = present_results(
    all_results,
    val_method="lnpo",
    remove_xgboost=False,
    remove_chronos_small_from_test=True,
    average_over_seed=True,
    show_tests=False
)

                                                                                                                                                Seed  \
Aggregator         Dataset   Features     Label Name    Model              Resampling Side  Validation Channels Feature Scaling Sample Scaling
MeanChanAggregator usilaughs efficientnet cognitiveload LogisticRegression None       right LNPO       [1]      StandardScaler  empty_scaler     NaN
                                                                                                       [2]      StandardScaler  empty_scaler     NaN

                                                                                                                                               accuracy_score  \
Aggregator         Dataset   Features     Label Name    Model              Resampling Side  Validation Channels Feature Scaling Sample Scaling
MeanChanAggregator usilaughs efficientnet cognitiveload LogisticRegression None       right LNPO       [1]      StandardScaler  empty_scaler      0.72 ± 0.03
                                                                                                       [2]      StandardScaler  empty_scaler      0.64 ± 0.04

                                                                                                                                               balanced_accuracy_score  \
Aggregator         Dataset   Features     Label Name    Model              Resampling Side  Validation Channels Feature Scaling Sample Scaling
MeanChanAggregator usilaughs efficientnet cognitiveload LogisticRegression None       right LNPO       [1]      StandardScaler  empty_scaler               0.70 ± 0.04
                                                                                                       [2]      StandardScaler  empty_scaler               0.64 ± 0.04

                                                                                                                                                   f1_score  \
Aggregator         Dataset   Features     Label Name    Model              Resampling Side  Validation Channels Feature Scaling Sample Scaling
MeanChanAggregator usilaughs efficientnet cognitiveload LogisticRegression None       right LNPO       [1]      StandardScaler  empty_scaler    0.78 ± 0.02
                                                                                                       [2]      StandardScaler  empty_scaler    0.70 ± 0.03

                                                                                                                                               matthews_corrcoef  \
Aggregator         Dataset   Features     Label Name    Model              Resampling Side  Validation Channels Feature Scaling Sample Scaling
MeanChanAggregator usilaughs efficientnet cognitiveload LogisticRegression None       right LNPO       [1]      StandardScaler  empty_scaler         0.41 ± 0.07
                                                                                                       [2]      StandardScaler  empty_scaler         0.27 ± 0.08

                                                                                                                                               precision_score  \
Aggregator         Dataset   Features     Label Name    Model              Resampling Side  Validation Channels Feature Scaling Sample Scaling
MeanChanAggregator usilaughs efficientnet cognitiveload LogisticRegression None       right LNPO       [1]      StandardScaler  empty_scaler       0.82 ± 0.04
                                                                                                       [2]      StandardScaler  empty_scaler       0.79 ± 0.04

                                                                                                                                               recall_score  \
Aggregator         Dataset   Features     Label Name    Model              Resampling Side  Validation Channels Feature Scaling Sample Scaling
MeanChanAggregator usilaughs efficientnet cognitiveload LogisticRegression None       right LNPO       [1]      StandardScaler  empty_scaler    0.77 ± 0.05
                                                                                                       [2]      StandardScaler  empty_scaler    0.63 ± 0.05

                                                                                                                                               roc_auc_score
Aggregator         Dataset   Features     Label Name    Model              Resampling Side  Validation Channels Feature Scaling Sample Scaling
MeanChanAggregator usilaughs efficientnet cognitiveload LogisticRegression None       right LNPO       [1]      StandardScaler  empty_scaler     0.70 ± 0.04
                                                                                                       [2]      StandardScaler  empty_scaler     0.64 ± 0.04

# Others

In [ ]:
# TODO: `only_last` does not work as intended. It should consider only the last multirun for each
# dataset, regardless of the others.
all_results = get_results_path(only_last=True, specific_path="multirun_2025-11-04-14-36-07")

In [ ]:
# TODO: the error from the average over seed is not computed correctly.
results_lopo = present_results(
    all_results,
    val_method="lnpo",
    remove_xgboost=False,
    remove_chronos_small_from_test=True,
    average_over_seed=True,
    show_tests=False
)

In [ ]:
# TODO: the error from the average over seed is not computed correctly.
results_lopo = present_results(
    all_results,
    val_method="lnpo",
    remove_xgboost=False,
    remove_chronos_small_from_test=True,
    average_over_seed=True,
    show_tests=False
)

                                                                                                                                                 Seed  \
Aggregator         Dataset   Features                    Label Name    Model              Resampling Side  Validation Channels  Feature Scaling
MeanChanAggregator usilaughs amazon/chronos-t5-small     cognitiveload LogisticRegression None       right LNPO       [0, 1, 2] StandardScaler    NaN
                                                                                                                      [0]       StandardScaler    NaN
                                                                                                                      [1]       StandardScaler    NaN
                                                                                                                      [2]       StandardScaler    NaN
                             efficientnet                cognitiveload LogisticRegression None       right LNPO       [0, 1, 2] StandardScaler    NaN
                                                                                                                      [0]       StandardScaler    NaN
                                                                                                                      [1]       StandardScaler    NaN
                                                                                                                      [2]       StandardScaler    NaN
                             mae                         cognitiveload LogisticRegression None       right LNPO       [0, 1, 2] StandardScaler    NaN
                                                                                                                      [0]       StandardScaler    NaN
                                                                                                                      [1]       StandardScaler    NaN
                                                                                                                      [2]       StandardScaler    NaN
None               usilaughs HandcraftedFeatureExtractor cognitiveload DummyClassifier    None       right LNPO       [0, 1, 2] StandardScaler    NaN
                                                                                                                      [0]       StandardScaler    NaN
                                                                                                                      [1]       StandardScaler    NaN
                                                                                                                      [2]       StandardScaler    NaN
                                                                       LogisticRegression None       right LNPO       [0, 1, 2] StandardScaler    NaN
                                                                                                                      [0]       StandardScaler    NaN
                                                                                                                      [1]       StandardScaler    NaN
                                                                                                                      [2]       StandardScaler    NaN

                                                                                                                                                accuracy_score  \
Aggregator         Dataset   Features                    Label Name    Model              Resampling Side  Validation Channels  Feature Scaling
MeanChanAggregator usilaughs amazon/chronos-t5-small     cognitiveload LogisticRegression None       right LNPO       [0, 1, 2] StandardScaler     0.80 ± 0.04
                                                                                                                      [0]       StandardScaler     0.54 ± 0.17
                                                                                                                      [1]       StandardScaler     0.57 ± 0.09
                                                                                                                      [2]       StandardScaler     0.62 ± 0.13
                             efficientnet                cognitiveload LogisticRegression None       right LNPO       [0, 1, 2] StandardScaler     0.74 ± 0.04
                                                                                                                      [0]       StandardScaler     0.69 ± 0.07
                                                                                                                      [1]       StandardScaler     0.76 ± 0.06
                                                                                                                      [2]       StandardScaler     0.74 ± 0.07
                             mae                         cognitiveload LogisticRegression None       right LNPO       [0, 1, 2] StandardScaler     0.64 ± 0.03
                                                                                                                      [0]       StandardScaler     0.58 ± 0.07
                                                                                                                      [1]       StandardScaler     0.67 ± 0.05
                                                                                                                      [2]       StandardScaler     0.50 ± 0.09
None               usilaughs HandcraftedFeatureExtractor cognitiveload DummyClassifier    None       right LNPO       [0, 1, 2] StandardScaler     0.56 ± 0.00
                                                                                                                      [0]       StandardScaler     0.56 ± 0.00
                                                                                                                      [1]       StandardScaler     0.56 ± 0.00
                                                                                                                      [2]       StandardScaler     0.56 ± 0.00
                                                                       LogisticRegression None       right LNPO       [0, 1, 2] StandardScaler     0.74 ± 0.10
                                                                                                                      [0]       StandardScaler     0.72 ± 0.08
                                                                                                                      [1]       StandardScaler     0.77 ± 0.09
                                                                                                                      [2]       StandardScaler     0.70 ± 0.13

                                                                                                                                                balanced_accuracy_score  \
Aggregator         Dataset   Features                    Label Name    Model              Resampling Side  Validation Channels  Feature Scaling
MeanChanAggregator usilaughs amazon/chronos-t5-small     cognitiveload LogisticRegression None       right LNPO       [0, 1, 2] StandardScaler              0.74 ± 0.08
                                                                                                                      [0]       StandardScaler              0.56 ± 0.06
                                                                                                                      [1]       StandardScaler              0.63 ± 0.05
                                                                                                                      [2]       StandardScaler              0.61 ± 0.07
                             efficientnet                cognitiveload LogisticRegression None       right LNPO       [0, 1, 2] StandardScaler              0.73 ± 0.08
                                                                                                                      [0]       StandardScaler              0.67 ± 0.08
                                                                                                                      [1]       StandardScaler              0.71 ± 0.07
                                                                                                                      [2]       StandardScaler              0.72 ± 0.06
                             mae                         cognitiveload LogisticRegression None       right LNPO       [0, 1, 2] StandardScaler              0.57 ± 0.04
                                                                                                                      [0]       StandardScaler              0.52 ± 0.07
                                                                                                                      [1]       StandardScaler              0.60 ± 0.04
                                                                                                                      [2]       StandardScaler              0.50 ± 0.03
None               usilaughs HandcraftedFeatureExtractor cognitiveload DummyClassifier    None       right LNPO       [0, 1, 2] StandardScaler              0.62 ± 0.00
                                                                                                                      [0]       StandardScaler              0.62 ± 0.00
                                                                                                                      [1]       StandardScaler              0.62 ± 0.00
                                                                                                                      [2]       StandardScaler              0.62 ± 0.00
                                                                       LogisticRegression None       right LNPO       [0, 1, 2] StandardScaler              0.72 ± 0.14
                                                                                                                      [0]       StandardScaler              0.70 ± 0.10
                                                                                                                      [1]       StandardScaler              0.73 ± 0.11
                                                                                                                      [2]       StandardScaler              0.63 ± 0.15

                                                                                                                                                    f1_score  \
Aggregator         Dataset   Features                    Label Name    Model              Resampling Side  Validation Channels  Feature Scaling
MeanChanAggregator usilaughs amazon/chronos-t5-small     cognitiveload LogisticRegression None       right LNPO       [0, 1, 2] StandardScaler   0.86 ± 0.03
                                                                                                                      [0]       StandardScaler   0.47 ± 0.38
                                                                                                                      [1]       StandardScaler   0.54 ± 0.15
                                                                                                                      [2]       StandardScaler   0.63 ± 0.25
                             efficientnet                cognitiveload LogisticRegression None       right LNPO       [0, 1, 2] StandardScaler   0.80 ± 0.04
                                                                                                                      [0]       StandardScaler   0.76 ± 0.06
                                                                                                                      [1]       StandardScaler   0.82 ± 0.04
                                                                                                                      [2]       StandardScaler   0.80 ± 0.07
                             mae                         cognitiveload LogisticRegression None       right LNPO       [0, 1, 2] StandardScaler   0.75 ± 0.03
                                                                                                                      [0]       StandardScaler   0.68 ± 0.08
                                                                                                                      [1]       StandardScaler   0.76 ± 0.05
                                                                                                                      [2]       StandardScaler   0.54 ± 0.16
None               usilaughs HandcraftedFeatureExtractor cognitiveload DummyClassifier    None       right LNPO       [0, 1, 2] StandardScaler   0.56 ± 0.00
                                                                                                                      [0]       StandardScaler   0.56 ± 0.00
                                                                                                                      [1]       StandardScaler   0.56 ± 0.00
                                                                                                                      [2]       StandardScaler   0.56 ± 0.00
                                                                       LogisticRegression None       right LNPO       [0, 1, 2] StandardScaler   0.81 ± 0.07
                                                                                                                      [0]       StandardScaler   0.79 ± 0.06
                                                                                                                      [1]       StandardScaler   0.82 ± 0.08
                                                                                                                      [2]       StandardScaler   0.78 ± 0.10

                                                                                                                                                matthews_corrcoef  \
Aggregator         Dataset   Features                    Label Name    Model              Resampling Side  Validation Channels  Feature Scaling
MeanChanAggregator usilaughs amazon/chronos-t5-small     cognitiveload LogisticRegression None       right LNPO       [0, 1, 2] StandardScaler        0.56 ± 0.12
                                                                                                                      [0]       StandardScaler        0.13 ± 0.13
                                                                                                                      [1]       StandardScaler        0.29 ± 0.11
                                                                                                                      [2]       StandardScaler        0.28 ± 0.15
                             efficientnet                cognitiveload LogisticRegression None       right LNPO       [0, 1, 2] StandardScaler        0.47 ± 0.14
                                                                                                                      [0]       StandardScaler        0.33 ± 0.17
                                                                                                                      [1]       StandardScaler        0.44 ± 0.13
                                                                                                                      [2]       StandardScaler        0.47 ± 0.14
                             mae                         cognitiveload LogisticRegression None       right LNPO       [0, 1, 2] StandardScaler        0.15 ± 0.08
                                                                                                                      [0]       StandardScaler        0.05 ± 0.13
                                                                                                                      [1]       StandardScaler        0.22 ± 0.10
                                                                                                                      [2]       StandardScaler        0.00 ± 0.05
None               usilaughs HandcraftedFeatureExtractor cognitiveload DummyClassifier    None       right LNPO       [0, 1, 2] StandardScaler        0.25 ± 0.00
                                                                                                                      [0]       StandardScaler        0.25 ± 0.00
                                                                                                                      [1]       StandardScaler        0.25 ± 0.00
                                                                                                                      [2]       StandardScaler        0.25 ± 0.00
                                                                       LogisticRegression None       right LNPO       [0, 1, 2] StandardScaler        0.44 ± 0.28
                                                                                                                      [0]       StandardScaler        0.39 ± 0.19
                                                                                                                      [1]       StandardScaler        0.50 ± 0.20
                                                                                                                      [2]       StandardScaler        0.30 ± 0.31

                                                                                                                                                precision_score  \
Aggregator         Dataset   Features                    Label Name    Model              Resampling Side  Validation Channels  Feature Scaling
MeanChanAggregator usilaughs amazon/chronos-t5-small     cognitiveload LogisticRegression None       right LNPO       [0, 1, 2] StandardScaler      0.82 ± 0.09
                                                                                                                      [0]       StandardScaler      0.43 ± 0.35
                                                                                                                      [1]       StandardScaler      0.87 ± 0.11
                                                                                                                      [2]       StandardScaler      0.83 ± 0.14
                             efficientnet                cognitiveload LogisticRegression None       right LNPO       [0, 1, 2] StandardScaler      0.86 ± 0.10
                                                                                                                      [0]       StandardScaler      0.79 ± 0.05
                                                                                                                      [1]       StandardScaler      0.80 ± 0.05
                                                                                                                      [2]       StandardScaler      0.83 ± 0.05
                             mae                         cognitiveload LogisticRegression None       right LNPO       [0, 1, 2] StandardScaler      0.71 ± 0.03
                                                                                                                      [0]       StandardScaler      0.68 ± 0.05
                                                                                                                      [1]       StandardScaler      0.73 ± 0.02
                                                                                                                      [2]       StandardScaler      0.66 ± 0.03
None               usilaughs HandcraftedFeatureExtractor cognitiveload DummyClassifier    None       right LNPO       [0, 1, 2] StandardScaler      0.83 ± 0.00

In [3]:
# TODO: the error from the average over seed is not computed correctly.
results_lopo = present_results(
    all_results,
    val_method="lnpo",
    remove_xgboost=False,
    remove_chronos_small_from_test=True,
    average_over_seed=True,
    show_tests=False
)

                                                                                                                                                Seed  \
Aggregator         Dataset   Features                    Label Name    Model              Resampling Side  Validation Channels  Scaling
MeanChanAggregator usilaughs amazon/chronos-t5-small     cognitiveload LogisticRegression None       right LNPO       [0, 1, 2] StandardScaler   NaN
                                                                                                                      [0]       StandardScaler   NaN
                                                                                                                      [1]       StandardScaler   NaN
                                                                                                                      [2]       StandardScaler   NaN
                             efficientnet                cognitiveload LogisticRegression None       right LNPO       [0, 1, 2] StandardScaler   NaN
                                                                                                                      [0]       StandardScaler   NaN
                                                                                                                      [1]       StandardScaler   NaN
                                                                                                                      [2]       StandardScaler   NaN
                             mae                         cognitiveload LogisticRegression None       right LNPO       [0, 1, 2] StandardScaler   NaN
                                                                                                                      [0]       StandardScaler   NaN
                                                                                                                      [1]       StandardScaler   NaN
                                                                                                                      [2]       StandardScaler   NaN
None               usilaughs HandcraftedFeatureExtractor cognitiveload DummyClassifier    None       right LNPO       [0, 1, 2] StandardScaler   NaN
                                                                                                                      [0]       StandardScaler   NaN
                                                                                                                      [1]       StandardScaler   NaN
                                                                                                                      [2]       StandardScaler   NaN
                                                                       LogisticRegression None       right LNPO       [0, 1, 2] StandardScaler   NaN
                                                                                                                      [0]       StandardScaler   NaN
                                                                                                                      [1]       StandardScaler   NaN
                                                                                                                      [2]       StandardScaler   NaN

                                                                                                                                               accuracy_score  \
Aggregator         Dataset   Features                    Label Name    Model              Resampling Side  Validation Channels  Scaling
MeanChanAggregator usilaughs amazon/chronos-t5-small     cognitiveload LogisticRegression None       right LNPO       [0, 1, 2] StandardScaler    0.80 ± 0.04
                                                                                                                      [0]       StandardScaler    0.54 ± 0.17
                                                                                                                      [1]       StandardScaler    0.57 ± 0.09
                                                                                                                      [2]       StandardScaler    0.62 ± 0.13
                             efficientnet                cognitiveload LogisticRegression None       right LNPO       [0, 1, 2] StandardScaler    0.67 ± 0.08
                                                                                                                      [0]       StandardScaler    0.67 ± 0.06
                                                                                                                      [1]       StandardScaler    0.64 ± 0.06
                                                                                                                      [2]       StandardScaler    0.68 ± 0.08
                             mae                         cognitiveload LogisticRegression None       right LNPO       [0, 1, 2] StandardScaler    0.64 ± 0.03
                                                                                                                      [0]       StandardScaler    0.58 ± 0.07
                                                                                                                      [1]       StandardScaler    0.67 ± 0.05
                                                                                                                      [2]       StandardScaler    0.50 ± 0.09
None               usilaughs HandcraftedFeatureExtractor cognitiveload DummyClassifier    None       right LNPO       [0, 1, 2] StandardScaler    0.56 ± 0.00
                                                                                                                      [0]       StandardScaler    0.56 ± 0.00
                                                                                                                      [1]       StandardScaler    0.56 ± 0.00
                                                                                                                      [2]       StandardScaler    0.56 ± 0.00
                                                                       LogisticRegression None       right LNPO       [0, 1, 2] StandardScaler    0.74 ± 0.10
                                                                                                                      [0]       StandardScaler    0.72 ± 0.08
                                                                                                                      [1]       StandardScaler    0.77 ± 0.09
                                                                                                                      [2]       StandardScaler    0.70 ± 0.13

                                                                                                                                               balanced_accuracy_score  \
Aggregator         Dataset   Features                    Label Name    Model              Resampling Side  Validation Channels  Scaling
MeanChanAggregator usilaughs amazon/chronos-t5-small     cognitiveload LogisticRegression None       right LNPO       [0, 1, 2] StandardScaler             0.74 ± 0.08
                                                                                                                      [0]       StandardScaler             0.56 ± 0.06
                                                                                                                      [1]       StandardScaler             0.63 ± 0.05
                                                                                                                      [2]       StandardScaler             0.61 ± 0.07
                             efficientnet                cognitiveload LogisticRegression None       right LNPO       [0, 1, 2] StandardScaler             0.67 ± 0.11
                                                                                                                      [0]       StandardScaler             0.69 ± 0.08
                                                                                                                      [1]       StandardScaler             0.66 ± 0.10
                                                                                                                      [2]       StandardScaler             0.69 ± 0.07
                             mae                         cognitiveload LogisticRegression None       right LNPO       [0, 1, 2] StandardScaler             0.57 ± 0.04
                                                                                                                      [0]       StandardScaler             0.52 ± 0.07
                                                                                                                      [1]       StandardScaler             0.60 ± 0.04
                                                                                                                      [2]       StandardScaler             0.50 ± 0.03
None               usilaughs HandcraftedFeatureExtractor cognitiveload DummyClassifier    None       right LNPO       [0, 1, 2] StandardScaler             0.62 ± 0.00
                                                                                                                      [0]       StandardScaler             0.62 ± 0.00
                                                                                                                      [1]       StandardScaler             0.62 ± 0.00
                                                                                                                      [2]       StandardScaler             0.62 ± 0.00
                                                                       LogisticRegression None       right LNPO       [0, 1, 2] StandardScaler             0.72 ± 0.14
                                                                                                                      [0]       StandardScaler             0.70 ± 0.10
                                                                                                                      [1]       StandardScaler             0.73 ± 0.11
                                                                                                                      [2]       StandardScaler             0.63 ± 0.15

                                                                                                                                                   f1_score  \
Aggregator         Dataset   Features                    Label Name    Model              Resampling Side  Validation Channels  Scaling
MeanChanAggregator usilaughs amazon/chronos-t5-small     cognitiveload LogisticRegression None       right LNPO       [0, 1, 2] StandardScaler  0.86 ± 0.03
                                                                                                                      [0]       StandardScaler  0.47 ± 0.38
                                                                                                                      [1]       StandardScaler  0.54 ± 0.15
                                                                                                                      [2]       StandardScaler  0.63 ± 0.25
                             efficientnet                cognitiveload LogisticRegression None       right LNPO       [0, 1, 2] StandardScaler  0.72 ± 0.09
                                                                                                                      [0]       StandardScaler  0.71 ± 0.05
                                                                                                                      [1]       StandardScaler  0.70 ± 0.04
                                                                                                                      [2]       StandardScaler  0.72 ± 0.08
                             mae                         cognitiveload LogisticRegression None       right LNPO       [0, 1, 2] StandardScaler  0.75 ± 0.03
                                                                                                                      [0]       StandardScaler  0.68 ± 0.08
                                                                                                                      [1]       StandardScaler  0.76 ± 0.05
                                                                                                                      [2]       StandardScaler  0.54 ± 0.16
None               usilaughs HandcraftedFeatureExtractor cognitiveload DummyClassifier    None       right LNPO       [0, 1, 2] StandardScaler  0.56 ± 0.00
                                                                                                                      [0]       StandardScaler  0.56 ± 0.00
                                                                                                                      [1]       StandardScaler  0.56 ± 0.00
                                                                                                                      [2]       StandardScaler  0.56 ± 0.00
                                                                       LogisticRegression None       right LNPO       [0, 1, 2] StandardScaler  0.81 ± 0.07
                                                                                                                      [0]       StandardScaler  0.79 ± 0.06
                                                                                                                      [1]       StandardScaler  0.82 ± 0.08
                                                                                                                      [2]       StandardScaler  0.78 ± 0.10

                                                                                                                                               matthews_corrcoef  \
Aggregator         Dataset   Features                    Label Name    Model              Resampling Side  Validation Channels  Scaling
MeanChanAggregator usilaughs amazon/chronos-t5-small     cognitiveload LogisticRegression None       right LNPO       [0, 1, 2] StandardScaler       0.56 ± 0.12
                                                                                                                      [0]       StandardScaler       0.13 ± 0.13
                                                                                                                      [1]       StandardScaler       0.29 ± 0.11
                                                                                                                      [2]       StandardScaler       0.28 ± 0.15
                             efficientnet                cognitiveload LogisticRegression None       right LNPO       [0, 1, 2] StandardScaler       0.34 ± 0.20
                                                                                                                      [0]       StandardScaler       0.37 ± 0.16
                                                                                                                      [1]       StandardScaler       0.31 ± 0.18
                                                                                                                      [2]       StandardScaler       0.37 ± 0.14
                             mae                         cognitiveload LogisticRegression None       right LNPO       [0, 1, 2] StandardScaler       0.15 ± 0.08
                                                                                                                      [0]       StandardScaler       0.05 ± 0.13
                                                                                                                      [1]       StandardScaler       0.22 ± 0.10
                                                                                                                      [2]       StandardScaler       0.00 ± 0.05
None               usilaughs HandcraftedFeatureExtractor cognitiveload DummyClassifier    None       right LNPO       [0, 1, 2] StandardScaler       0.25 ± 0.00
                                                                                                                      [0]       StandardScaler       0.25 ± 0.00
                                                                                                                      [1]       StandardScaler       0.25 ± 0.00
                                                                                                                      [2]       StandardScaler       0.25 ± 0.00
                                                                       LogisticRegression None       right LNPO       [0, 1, 2] StandardScaler       0.44 ± 0.28
                                                                                                                      [0]       StandardScaler       0.39 ± 0.19
                                                                                                                      [1]       StandardScaler       0.50 ± 0.20
                                                                                                                      [2]       StandardScaler       0.30 ± 0.31

                                                                                                                                               precision_score  \
Aggregator         Dataset   Features                    Label Name    Model              Resampling Side  Validation Channels  Scaling
MeanChanAggregator usilaughs amazon/chronos-t5-small     cognitiveload LogisticRegression None       right LNPO       [0, 1, 2] StandardScaler     0.82 ± 0.09
                                                                                                                      [0]       StandardScaler     0.43 ± 0.35
                                                                                                                      [1]       StandardScaler     0.87 ± 0.11
                                                                                                                      [2]       StandardScaler     0.83 ± 0.14
                             efficientnet                cognitiveload LogisticRegression None       right LNPO       [0, 1, 2] StandardScaler     0.84 ± 0.14
                                                                                                                      [0]       StandardScaler     0.85 ± 0.10
                                                                                                                      [1]       StandardScaler     0.83 ± 0.11
                                                                                                                      [2]       StandardScaler     0.83 ± 0.05
                             mae                         cognitiveload LogisticRegression None       right LNPO       [0, 1, 2] StandardScaler     0.71 ± 0.03
                                                                                                                      [0]       StandardScaler     0.68 ± 0.05
                                                                                                                      [1]       StandardScaler     0.73 ± 0.02
                                                                                                                      [2]       StandardScaler     0.66 ± 0.03
None               usilaughs HandcraftedFeatureExtractor cognitiveload DummyClassifier    None       right LNPO       [0, 1, 2] StandardScaler     0.83 ± 0.00
                                                                                                                      [0]       StandardScaler     0.83 ± 0.00
                                                                                                                      [1]       StandardScaler     0.83 ± 0.00

In [4]:
# TODO: the error from the average over seed is not computed correctly.
results_lopo = present_results(
    all_results,
    val_method="tacv",
    remove_xgboost=False,
    remove_chronos_small_from_test=True,
    average_over_seed=True,
)

KeyError: 'Dataset'