In [5]:
from sys import path

path.append("../")

from src.utils.result_presentation import get_results_path, present_results

In [6]:
# TODO: `only_last` does not work as intended. It should consider only the last multirun for each
# dataset, regardless of the others.
all_results = get_results_path(only_last=True, specific_path="multirun_2025-09-30-11-18-53")

In [7]:
# TODO: the error from the average over seed is not computed correctly.
results_lopo = present_results(
    all_results,
    val_method="lnpo",
    remove_xgboost=True,
    remove_chronos_small_from_test=True,
    average_over_seed=True,
)

                                                                                                                                    Seed  \
Aggregator         Dataset Features                                    Label Name Model              Resampling Side    Validation
MeanChanAggregator seed    ibm-granite/granite-timeseries-patchtsmixer engagement LogisticRegression None       unknown LNPO         NaN
None               seed    HandcraftedFeatureExtractor                 engagement DummyClassifier    None       unknown LNPO         NaN
                                                                                  LogisticRegression None       unknown LNPO         NaN

                                                                                                                                   accuracy_score  \
Aggregator         Dataset Features                                    Label Name Model              Resampling Side    Validation
MeanChanAggregator seed    ibm-granite/granite-timeseries-patchtsmixer engagement LogisticRegression None       unknown LNPO          0.55 ± 0.04
None               seed    HandcraftedFeatureExtractor                 engagement DummyClassifier    None       unknown LNPO          0.55 ± 0.04
                                                                                  LogisticRegression None       unknown LNPO          0.55 ± 0.04

                                                                                                                                   balanced_accuracy_score  \
Aggregator         Dataset Features                                    Label Name Model              Resampling Side    Validation
MeanChanAggregator seed    ibm-granite/granite-timeseries-patchtsmixer engagement LogisticRegression None       unknown LNPO                   0.48 ± 0.02
None               seed    HandcraftedFeatureExtractor                 engagement DummyClassifier    None       unknown LNPO                   0.50 ± 0.02
                                                                                  LogisticRegression None       unknown LNPO                   0.47 ± 0.02

                                                                                                                                       f1_score  \
Aggregator         Dataset Features                                    Label Name Model              Resampling Side    Validation
MeanChanAggregator seed    ibm-granite/granite-timeseries-patchtsmixer engagement LogisticRegression None       unknown LNPO        0.68 ± 0.04
None               seed    HandcraftedFeatureExtractor                 engagement DummyClassifier    None       unknown LNPO        0.64 ± 0.05
                                                                                  LogisticRegression None       unknown LNPO        0.68 ± 0.04

                                                                                                                                   matthews_corrcoef  \
Aggregator         Dataset Features                                    Label Name Model              Resampling Side    Validation
MeanChanAggregator seed    ibm-granite/granite-timeseries-patchtsmixer engagement LogisticRegression None       unknown LNPO            -0.05 ± 0.04
None               seed    HandcraftedFeatureExtractor                 engagement DummyClassifier    None       unknown LNPO            -0.00 ± 0.05
                                                                                  LogisticRegression None       unknown LNPO            -0.08 ± 0.03

                                                                                                                                   precision_score  \
Aggregator         Dataset Features                                    Label Name Model              Resampling Side    Validation
MeanChanAggregator seed    ibm-granite/granite-timeseries-patchtsmixer engagement LogisticRegression None       unknown LNPO           0.62 ± 0.05
None               seed    HandcraftedFeatureExtractor                 engagement DummyClassifier    None       unknown LNPO           0.64 ± 0.06
                                                                                  LogisticRegression None       unknown LNPO           0.61 ± 0.05

                                                                                                                                   recall_score  \
Aggregator         Dataset Features                                    Label Name Model              Resampling Side    Validation
MeanChanAggregator seed    ibm-granite/granite-timeseries-patchtsmixer engagement LogisticRegression None       unknown LNPO        0.81 ± 0.04
None               seed    HandcraftedFeatureExtractor                 engagement DummyClassifier    None       unknown LNPO        0.70 ± 0.07
                                                                                  LogisticRegression None       unknown LNPO        0.84 ± 0.05

                                                                                                                                   roc_auc_score
Aggregator         Dataset Features                                    Label Name Model              Resampling Side    Validation
MeanChanAggregator seed    ibm-granite/granite-timeseries-patchtsmixer engagement LogisticRegression None       unknown LNPO         0.48 ± 0.02
None               seed    HandcraftedFeatureExtractor                 engagement DummyClassifier    None       unknown LNPO         0.50 ± 0.02
                                                                                  LogisticRegression None       unknown LNPO         0.46 ± 0.01

Friedman Test accuracy_score: statistic=1.600, pvalue=0.449
Nemenyi post-hoc test

                                                                           DummyClassifier  \
                                                               HandcraftedFeatureExtractor
DummyClassifier    HandcraftedFeatureExtractor                                    1.000000
LogisticRegression HandcraftedFeatureExtractor                                    0.415114
                   ibm-granite/granite-timeseries-patchtsmixer                    0.802241

                                                                        LogisticRegression  \
                                                               HandcraftedFeatureExtractor
DummyClassifier    HandcraftedFeatureExtractor                                    0.415114
LogisticRegression HandcraftedFeatureExtractor                                    1.000000
                   ibm-granite/granite-timeseries-patchtsmixer                    0.802241


                                                               ibm-granite/granite-timeseries-patchtsmixer
DummyClassifier    HandcraftedFeatureExtractor                                                    0.802241
LogisticRegression HandcraftedFeatureExtractor                                                    0.802241
                   ibm-granite/granite-timeseries-patchtsmixer                                    1.000000

Friedman Test balanced_accuracy_score: statistic=2.800, pvalue=0.247
Nemenyi post-hoc test

                                                                           DummyClassifier  \
                                                               HandcraftedFeatureExtractor
DummyClassifier    HandcraftedFeatureExtractor                                    1.000000
LogisticRegression HandcraftedFeatureExtractor                                    0.253784
                   ibm-granite/granite-timeseries-patchtsmixer                    0.415114

                                                                        LogisticRegression  \
                                                               HandcraftedFeatureExtractor
DummyClassifier    HandcraftedFeatureExtractor                                    0.253784
LogisticRegression HandcraftedFeatureExtractor                                    1.000000
                   ibm-granite/granite-timeseries-patchtsmixer                    0.946370


                                                               ibm-granite/granite-timeseries-patchtsmixer
DummyClassifier    HandcraftedFeatureExtractor                                                    0.415114
LogisticRegression HandcraftedFeatureExtractor                                                    0.946370
                   ibm-granite/granite-timeseries-patchtsmixer                                    1.000000

Friedman Test matthews_corrcoef: statistic=2.800, pvalue=0.247
Nemenyi post-hoc test

                                                                           DummyClassifier  \
                                                               HandcraftedFeatureExtractor
DummyClassifier    HandcraftedFeatureExtractor                                    1.000000
LogisticRegression HandcraftedFeatureExtractor                                    0.253784
                   ibm-granite/granite-timeseries-patchtsmixer                    0.415114

                                                                        LogisticRegression  \
                                                               HandcraftedFeatureExtractor
DummyClassifier    HandcraftedFeatureExtractor                                    0.253784
LogisticRegression HandcraftedFeatureExtractor                                    1.000000
                   ibm-granite/granite-timeseries-patchtsmixer                    0.946370


                                                               ibm-granite/granite-timeseries-patchtsmixer
DummyClassifier    HandcraftedFeatureExtractor                                                    0.415114
LogisticRegression HandcraftedFeatureExtractor                                                    0.946370
                   ibm-granite/granite-timeseries-patchtsmixer                                    1.000000

Friedman Test f1_score: statistic=0.400, pvalue=0.819
Nemenyi post-hoc test

                                                                           DummyClassifier  \
                                                               HandcraftedFeatureExtractor
DummyClassifier    HandcraftedFeatureExtractor                                     1.00000
LogisticRegression HandcraftedFeatureExtractor                                     0.94637
                   ibm-granite/granite-timeseries-patchtsmixer                     0.94637

                                                                        LogisticRegression  \
                                                               HandcraftedFeatureExtractor
DummyClassifier    HandcraftedFeatureExtractor                                    0.946370
LogisticRegression HandcraftedFeatureExtractor                                    1.000000
                   ibm-granite/granite-timeseries-patchtsmixer                    0.802241


                                                               ibm-granite/granite-timeseries-patchtsmixer
DummyClassifier    HandcraftedFeatureExtractor                                                    0.946370
LogisticRegression HandcraftedFeatureExtractor                                                    0.802241
                   ibm-granite/granite-timeseries-patchtsmixer                                    1.000000

Friedman Test precision_score: statistic=2.800, pvalue=0.247
Nemenyi post-hoc test

                                                                           DummyClassifier  \
                                                               HandcraftedFeatureExtractor
DummyClassifier    HandcraftedFeatureExtractor                                    1.000000
LogisticRegression HandcraftedFeatureExtractor                                    0.253784
                   ibm-granite/granite-timeseries-patchtsmixer                    0.415114

                                                                        LogisticRegression  \
                                                               HandcraftedFeatureExtractor
DummyClassifier    HandcraftedFeatureExtractor                                    0.253784
LogisticRegression HandcraftedFeatureExtractor                                    1.000000
                   ibm-granite/granite-timeseries-patchtsmixer                    0.946370


                                                               ibm-granite/granite-timeseries-patchtsmixer
DummyClassifier    HandcraftedFeatureExtractor                                                    0.415114
LogisticRegression HandcraftedFeatureExtractor                                                    0.946370
                   ibm-granite/granite-timeseries-patchtsmixer                                    1.000000

Friedman Test recall_score: statistic=0.737, pvalue=0.692
Nemenyi post-hoc test

                                                                           DummyClassifier  \
                                                               HandcraftedFeatureExtractor
DummyClassifier    HandcraftedFeatureExtractor                                    1.000000
LogisticRegression HandcraftedFeatureExtractor                                    0.986312
                   ibm-granite/granite-timeseries-patchtsmixer                    0.708838

                                                                        LogisticRegression  \
                                                               HandcraftedFeatureExtractor
DummyClassifier    HandcraftedFeatureExtractor                                    0.986312
LogisticRegression HandcraftedFeatureExtractor                                    1.000000
                   ibm-granite/granite-timeseries-patchtsmixer                    0.802241


                                                               ibm-granite/granite-timeseries-patchtsmixer
DummyClassifier    HandcraftedFeatureExtractor                                                    0.708838
LogisticRegression HandcraftedFeatureExtractor                                                    0.802241
                   ibm-granite/granite-timeseries-patchtsmixer                                    1.000000

Friedman Test roc_auc_score: statistic=2.800, pvalue=0.247
Nemenyi post-hoc test

                                                                           DummyClassifier  \
                                                               HandcraftedFeatureExtractor
DummyClassifier    HandcraftedFeatureExtractor                                    1.000000
LogisticRegression HandcraftedFeatureExtractor                                    0.253784
                   ibm-granite/granite-timeseries-patchtsmixer                    0.415114

                                                                        LogisticRegression  \
                                                               HandcraftedFeatureExtractor
DummyClassifier    HandcraftedFeatureExtractor                                    0.253784
LogisticRegression HandcraftedFeatureExtractor                                    1.000000
                   ibm-granite/granite-timeseries-patchtsmixer                    0.946370


                                                               ibm-granite/granite-timeseries-patchtsmixer
DummyClassifier    HandcraftedFeatureExtractor                                                    0.415114
LogisticRegression HandcraftedFeatureExtractor                                                    0.946370
                   ibm-granite/granite-timeseries-patchtsmixer                                    1.000000